#!/usr/bin/env node
'use strict';

/**
 * Lari self-teaching coding loop.
 *
 * The thesis: Lari does not learn to code from reading code. It learns by
 * doing — generate a task, attempt it, run the code in a sandbox, verify the
 * output, retain what works, study what fails.
 *
 * Every retained solution is verified working, not pattern-matched. Slower
 * than an LLM at first. But the slowness disappears once the library exists:
 * then it is instant recall of proven code.
 *
 * Cycle:
 *   1. Task: from the seed library, or generated by composing mastered tasks.
 *   2. Attempt: known solutions first, then pattern composition, then mutation.
 *   3. Verify: run in a sandbox with a timeout, compare against the task's
 *      oracle (expected stdout or a test snippet).
 *   4. Learn: success -> solution retained permanently in
 *      model.lariCodeGeneration.solutions. Failure -> recorded with the error,
 *      becomes a learning goal for the research loop.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

// ---------------------------------------------------------------------------
// Sandbox execution
// ---------------------------------------------------------------------------

const LANGUAGE_RUNNERS = {
  python: { command: 'python3', args: [], ext: '.py' },
  javascript: { command: 'node', args: [], ext: '.js' },
  go: { command: 'go', args: ['run'], ext: '.go' }
};

/**
 * Run code in a sandbox: temp dir, hard timeout, stdout/stderr captured.
 * Returns { ok, stdout, stderr, exitCode, timedOut }.
 */
function runCodeSandbox(language, code, options = {}) {
  const runner = LANGUAGE_RUNNERS[language];
  if (!runner) return { ok: false, stdout: '', stderr: `unsupported language: ${language}`, exitCode: -1, timedOut: false };
  const timeoutMs = options.timeoutMs || 10000;
  let dir = null;
  try {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lari-code-'));
    const file = path.join(dir, `task${runner.ext}`);
    fs.writeFileSync(file, String(code || ''));
    const run = spawnSync(runner.command, [...runner.args, file, ...(options.args || [])], {
      cwd: dir, encoding: 'utf8', timeout: timeoutMs, windowsHide: true,
      maxBuffer: 1024 * 1024
    });
    const timedOut = run.error && (run.error.code === 'ETIMEDOUT' || /timed out/i.test(run.error.message || ''));
    return {
      ok: !timedOut && run.status === 0,
      stdout: String(run.stdout || ''),
      stderr: String(run.stderr || ''),
      exitCode: run.status,
      timedOut: !!timedOut
    };
  } catch (error) {
    return { ok: false, stdout: '', stderr: String((error && error.message) || error), exitCode: -1, timedOut: false };
  } finally {
    if (dir) { try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) {} }
  }
}

// ---------------------------------------------------------------------------
// Seed task library: tasks Lari can practice on from day one.
// Each task has a verifiable oracle — no human judgment needed.
// ---------------------------------------------------------------------------

const CODE_TASK_SEEDS = [
  {
    id: 'py-fibonacci-10',
    language: 'python',
    description: 'print the first 10 fibonacci numbers, one per line',
    tags: ['sequence', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '0\n1\n1\n2\n3\n5\n8\n13\n21\n34' }
  },
  {
    id: 'py-fizzbuzz-15',
    language: 'python',
    description: 'print fizzbuzz from 1 to 15, one per line',
    tags: ['loop', 'condition'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz' }
  },
  {
    id: 'py-factorial-5',
    language: 'python',
    description: 'print the factorial of 5',
    tags: ['math', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '120' }
  },
  {
    id: 'py-palindrome',
    language: 'python',
    description: 'print True if "racecar" is a palindrome else False',
    tags: ['string', 'condition'],
    difficulty: 1,
    verify: { type: 'stdout', expected: 'True' }
  },
  {
    id: 'py-sum-list',
    language: 'python',
    description: 'print the sum of the numbers 1 through 100',
    tags: ['math', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '5050' }
  },
  {
    id: 'py-reverse-string',
    language: 'python',
    description: 'print "hello" reversed',
    tags: ['string'],
    difficulty: 1,
    verify: { type: 'stdout', expected: 'olleh' }
  },
  {
    id: 'py-even-numbers',
    language: 'python',
    description: 'print the even numbers from 2 to 20, one per line',
    tags: ['loop', 'condition'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '2\n4\n6\n8\n10\n12\n14\n16\n18\n20' }
  },
  {
    id: 'py-prime-check',
    language: 'python',
    description: 'print True if 17 is prime else False',
    tags: ['math', 'loop', 'condition'],
    difficulty: 2,
    verify: { type: 'stdout', expected: 'True' }
  },
  {
    id: 'py-count-vowels',
    language: 'python',
    description: 'print the number of vowels in "hello world"',
    tags: ['string', 'loop'],
    difficulty: 2,
    verify: { type: 'stdout', expected: '3' }
  },
  {
    id: 'py-max-list',
    language: 'python',
    description: 'print the largest number in [3, 7, 2, 9, 4]',
    tags: ['list', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '9' }
  },
  {
    id: 'js-fibonacci-10',
    language: 'javascript',
    description: 'print the first 10 fibonacci numbers, one per line',
    tags: ['sequence', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '0\n1\n1\n2\n3\n5\n8\n13\n21\n34' }
  },
  {
    id: 'js-fizzbuzz-15',
    language: 'javascript',
    description: 'print fizzbuzz from 1 to 15, one per line',
    tags: ['loop', 'condition'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz' }
  },
  {
    id: 'js-sum-list',
    language: 'javascript',
    description: 'print the sum of the numbers 1 through 100',
    tags: ['math', 'loop'],
    difficulty: 1,
    verify: { type: 'stdout', expected: '5050' }
  }
];

// ---------------------------------------------------------------------------
// Candidate generation: known solutions, then pattern composition.
// ---------------------------------------------------------------------------

/**
 * Get retained solutions from the model.
 */
function getRetainedSolutions(model) {
  try {
    const sols = model && model.lariCodeGeneration && model.lariCodeGeneration.solutions;
    return Array.isArray(sols) ? sols : [];
  } catch (_) { return []; }
}

/**
 * Learned patterns: code templates Lari derived from research and verified in
 * the sandbox. Unlike CODE_PATTERNS (hardcoded reflexes), these are data —
 * they persist in the model and survive serialization. Each is
 * { id, language, matchSource (regex source), code, learnedFrom, verifiedAt }.
 */
function getLearnedPatterns(model) {
  const cg = model && model.lariCodeGeneration;
  return (cg && Array.isArray(cg.learnedPatterns)) ? cg.learnedPatterns : [];
}

function addLearnedPattern(model, pattern) {
  const cg = ensureCodeGeneration(model);
  if (!Array.isArray(cg.learnedPatterns)) cg.learnedPatterns = [];
  if (!cg.learnedPatterns.some(p => p.id === pattern.id)) {
    cg.learnedPatterns.push(pattern);
  }
  return pattern;
}

/**
 * Generalize verified code into a reusable template. Numbers in the code that
 * correspond to numbers in the task description (or ±1 off, the classic
 * range fencepost) become slots, so the pattern adapts to sibling tasks like
 * "first 8" → "first 5". Numbers with no link to the description stay literal.
 */
function generalizePattern(task, code) {
  const descNums = [...new Set((String(task.description || '').match(/\d+/g) || []).map(Number))];
  let template = String(code);
  const slots = [];
  for (const n of descNums) {
    for (const variant of [n, n + 1, n - 1]) {
      const re = new RegExp(`\\b${variant}\\b`);
      if (re.test(template)) {
        const slot = `__LARI_N${slots.length}__`;
        template = template.replace(new RegExp(`\\b${variant}\\b`, 'g'), slot);
        slots.push({ slot, base: n, offset: variant - n });
        break;
      }
    }
  }
  return { template, slots, originalDescription: String(task.description || '') };
}

/**
 * Instantiate a generalized learned pattern for a new task: map the new
 * task's numbers onto the slots in description order.
 */
function instantiateLearnedPattern(pattern, task) {
  if (!pattern.template) return pattern.code || null; // legacy literal pattern
  const newNums = (String(task.description || '').match(/\d+/g) || []).map(Number);
  const oldNums = (String(pattern.originalDescription || '').match(/\d+/g) || []).map(Number);
  let code = pattern.template;
  for (const s of (pattern.slots || [])) {
    const idx = oldNums.indexOf(s.base);
    const n = (idx >= 0 && idx < newNums.length) ? newNums[idx] : s.base;
    code = code.split(s.slot).join(String(n + s.offset));
  }
  // If slots remain unfilled something went wrong; do not emit broken code.
  if (/__LARI_N\d+__/.test(code)) return null;
  return code;
}

/**
 * Find a retained solution matching a task (by task id or description similarity).
 */
function findRetainedSolution(model, task) {
  const solutions = getRetainedSolutions(model);
  // Exact task id match first.
  for (const s of solutions) {
    if (s.taskId === task.id) return s;
  }
  // Then fuzzy: same language + overlapping tags + similar description.
  const taskWords = new Set(String(task.description || '').toLowerCase().split(/\W+/).filter(w => w.length > 3));
  let best = null, bestScore = 0;
  for (const s of solutions) {
    if (s.language !== task.language) continue;
    const sWords = new Set(String(s.description || '').toLowerCase().split(/\W+/).filter(w => w.length > 3));
    let overlap = 0;
    for (const w of taskWords) if (sWords.has(w)) overlap++;
    const tagOverlap = (s.tags || []).filter(t => (task.tags || []).includes(t)).length;
    const score = overlap + tagOverlap * 2;
    if (score > bestScore && score >= 3) { best = s; bestScore = score; }
  }
  return best;
}

// Code patterns: the "innate reflexes". Each pattern is a template with slots.
// These are starting points, not the library — the library is built from
// verified solutions.
const CODE_PATTERNS = [
  {
    id: 'py-fib-loop',
    language: 'python',
    match: /fibonacci/i,
    build: (task) => {
      const n = (task.description.match(/first (\d+)/i) || [])[1] || '10';
      return `a, b = 0, 1\nfor _ in range(${n}):\n    print(a)\n    a, b = b, a + b`;
    }
  },
  {
    id: 'py-fizzbuzz',
    language: 'python',
    match: /fizzbuzz/i,
    build: (task) => {
      const n = (task.description.match(/1 to (\d+)/i) || [])[1] || '15';
      return `for i in range(1, ${n} + 1):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`;
    }
  },
  {
    id: 'py-factorial',
    language: 'python',
    match: /factorial/i,
    build: (task) => {
      const n = (task.description.match(/factorial of (\d+)/i) || [])[1] || '5';
      return `result = 1\nfor i in range(1, ${n} + 1):\n    result *= i\nprint(result)`;
    }
  },
  {
    id: 'py-palindrome',
    language: 'python',
    match: /palindrome/i,
    build: (task) => {
      const word = (task.description.match(/"([^"]+)"/) || [])[1] || 'racecar';
      return `word = "${word}"\nprint(word == word[::-1])`;
    }
  },
  {
    id: 'py-sum-range',
    language: 'python',
    match: /sum of.*\d+.*through.*\d+|sum.*1.*100/i,
    build: (task) => {
      const nums = task.description.match(/(\d+)\D+through\D+(\d+)/i);
      const lo = nums ? nums[1] : '1', hi = nums ? nums[2] : '100';
      return `print(sum(range(${lo}, ${hi} + 1)))`;
    }
  },
  {
    id: 'py-reverse',
    language: 'python',
    match: /reversed/i,
    build: (task) => {
      const word = (task.description.match(/"([^"]+)"/) || [])[1] || 'hello';
      return `print("${word}"[::-1])`;
    }
  },
  {
    id: 'py-even-range',
    language: 'python',
    match: /even numbers/i,
    build: (task) => {
      const nums = task.description.match(/(\d+) to (\d+)/i);
      const lo = nums ? nums[1] : '2', hi = nums ? nums[2] : '20';
      return `for i in range(${lo}, ${hi} + 1, 2):\n    print(i)`;
    }
  },
  {
    id: 'py-prime',
    language: 'python',
    match: /prime/i,
    build: (task) => {
      const n = (task.description.match(/(\d+) is prime/i) || [])[1] || '17';
      return `n = ${n}\nis_prime = n > 1\nfor i in range(2, int(n ** 0.5) + 1):\n    if n % i == 0:\n        is_prime = False\n        break\nprint(is_prime)`;
    }
  },
  {
    id: 'py-vowels',
    language: 'python',
    match: /vowels/i,
    build: (task) => {
      const text = (task.description.match(/"([^"]+)"/) || [])[1] || 'hello world';
      return `text = "${text}"\nprint(sum(1 for c in text.lower() if c in "aeiou"))`;
    }
  },
  {
    id: 'py-max',
    language: 'python',
    match: /largest|max/i,
    build: (task) => {
      const list = (task.description.match(/\[([^\]]+)\]/) || [])[0] || '[3, 7, 2, 9, 4]';
      return `print(max(${list}))`;
    }
  },
  {
    id: 'js-fib-loop',
    language: 'javascript',
    match: /fibonacci/i,
    build: (task) => {
      const n = (task.description.match(/first (\d+)/i) || [])[1] || '10';
      return `let a = 0, b = 1;\nfor (let i = 0; i < ${n}; i++) {\n  console.log(a);\n  [a, b] = [b, a + b];\n}`;
    }
  },
  {
    id: 'js-fizzbuzz',
    language: 'javascript',
    match: /fizzbuzz/i,
    build: (task) => {
      const n = (task.description.match(/1 to (\d+)/i) || [])[1] || '15';
      return `for (let i = 1; i <= ${n}; i++) {\n  if (i % 15 === 0) console.log("FizzBuzz");\n  else if (i % 3 === 0) console.log("Fizz");\n  else if (i % 5 === 0) console.log("Buzz");\n  else console.log(i);\n}`;
    }
  },
  {
    id: 'js-sum-range',
    language: 'javascript',
    match: /sum of.*\d+.*through.*\d+|sum.*1.*100/i,
    build: (task) => {
      const nums = task.description.match(/(\d+)\D+through\D+(\d+)/i);
      const lo = nums ? nums[1] : '1', hi = nums ? nums[2] : '100';
      return `let sum = 0;\nfor (let i = ${lo}; i <= ${hi}; i++) sum += i;\nconsole.log(sum);`;
    }
  }
];

/**
 * Generate candidate code for a task. Returns array of { code, source }.
 * Order: retained solutions first, then pattern matches.
 */
function generateCandidates(model, task) {
  const candidates = [];
  const retained = findRetainedSolution(model, task);
  if (retained && retained.code) {
    candidates.push({ code: retained.code, source: `retained:${retained.taskId}` });
  }
  for (const pattern of CODE_PATTERNS) {
    if (pattern.language !== task.language) continue;
    if (!pattern.match.test(task.description || '')) continue;
    try {
      const code = pattern.build(task);
      if (code && !candidates.some(c => c.code === code)) {
        candidates.push({ code, source: `pattern:${pattern.id}` });
      }
    } catch (_) {}
  }
  // Learned patterns: derived from research, verified in the sandbox.
  for (const lp of getLearnedPatterns(model)) {
    if (lp.language !== task.language) continue;
    try {
      const re = new RegExp(lp.matchSource, 'i');
      if (!re.test(task.description || '')) continue;
      const code = instantiateLearnedPattern(lp, task);
      if (code && !candidates.some(c => c.code === code)) {
        candidates.push({ code, source: `learned:${lp.id}` });
      }
    } catch (_) {}
  }
  return candidates;
}

// ---------------------------------------------------------------------------
// Verification
// ---------------------------------------------------------------------------

function normalizeOutput(text) {
  return String(text || '').replace(/\r\n/g, '\n').trim().replace(/\n+$/, '');
}

function verifyAttempt(task, runResult) {
  if (!runResult) return { passed: false, reason: 'no_result' };
  if (runResult.timedOut) return { passed: false, reason: 'timeout', detail: runResult.stderr.slice(0, 200) };
  if (!runResult.ok) {
    return { passed: false, reason: 'runtime_error', detail: (runResult.stderr || '').slice(0, 300) };
  }
  const verify = task.verify || {};
  if (verify.type === 'stdout') {
    const actual = normalizeOutput(runResult.stdout);
    const expected = normalizeOutput(verify.expected);
    if (actual === expected) return { passed: true, reason: 'output_match' };
    return { passed: false, reason: 'output_mismatch', detail: `expected ${JSON.stringify(expected.slice(0, 100))}, got ${JSON.stringify(actual.slice(0, 100))}` };
  }
  if (verify.type === 'exit_code') {
    const expected = verify.expected == null ? 0 : verify.expected;
    if (runResult.exitCode === expected) return { passed: true, reason: 'exit_code_match' };
    return { passed: false, reason: 'exit_code_mismatch', detail: `exit ${runResult.exitCode}, stderr: ${(runResult.stderr || '').slice(0, 200)}` };
  }
  return { passed: false, reason: 'unknown_verify_type' };
}

// ---------------------------------------------------------------------------
// The self-teaching loop
// ---------------------------------------------------------------------------

function ensureCodeGeneration(model) {
  model.lariCodeGeneration = model.lariCodeGeneration || {};
  model.lariCodeGeneration.solutions = model.lariCodeGeneration.solutions || [];
  model.lariCodeGeneration.practiceLog = model.lariCodeGeneration.practiceLog || [];
  model.lariCodeGeneration.learningGoals = model.lariCodeGeneration.learningGoals || [];
  return model.lariCodeGeneration;
}

function retainSolution(model, task, code, source) {
  const cg = ensureCodeGeneration(model);
  // Do not duplicate.
  if (cg.solutions.some(s => s.taskId === task.id)) return false;
  cg.solutions.push({
    taskId: task.id,
    language: task.language,
    description: task.description,
    tags: task.tags || [],
    code: code,
    source: source,
    verifiedAt: new Date().toISOString(),
    verifyType: (task.verify || {}).type || 'stdout'
  });
  return true;
}

function logPractice(model, task, attempt) {
  const cg = ensureCodeGeneration(model);
  cg.practiceLog.push({
    taskId: task.id,
    timestamp: new Date().toISOString(),
    passed: attempt.verification.passed,
    reason: attempt.verification.reason,
    source: attempt.source
  });
  // Keep the log bounded.
  if (cg.practiceLog.length > 200) cg.practiceLog = cg.practiceLog.slice(-200);
}

function recordLearningGoal(model, task, failure) {
  const cg = ensureCodeGeneration(model);
  cg.learningGoals.push({
    taskId: task.id,
    description: task.description,
    language: task.language,
    tags: task.tags || [],
    failureReason: failure.reason,
    failureDetail: (failure.detail || '').slice(0, 200),
    // Carry the oracle so the research loop can verify against it later.
    expectedOutput: task.verify && task.verify.type === 'stdout' ? task.verify.expected : null,
    createdAt: new Date().toISOString(),
    status: 'open'
  });
  if (cg.learningGoals.length > 50) cg.learningGoals = cg.learningGoals.slice(-50);
}

/**
 * Teach one task: generate candidates, run each in the sandbox, verify.
 * Returns { taskId, passed, code, source, verification, attempts }.
 */
function selfTeachCodingTask(model, task, options = {}) {
  const maxAttempts = options.maxAttempts || 3;
  const candidates = generateCandidates(model, task);
  const result = {
    taskId: task.id,
    passed: false,
    code: null,
    source: null,
    verification: null,
    attempts: []
  };
  const tried = candidates.slice(0, maxAttempts);
  if (!tried.length) {
    result.verification = { passed: false, reason: 'no_candidates' };
    recordLearningGoal(model, task, result.verification);
    logPractice(model, task, result);
    return result;
  }
  for (const candidate of tried) {
    const runResult = runCodeSandbox(task.language, candidate.code, options);
    const verification = verifyAttempt(task, runResult);
    const attemptRecord = {
      source: candidate.source,
      code: candidate.code,
      runOk: runResult.ok,
      verification
    };
    result.attempts.push(attemptRecord);
    if (verification.passed) {
      result.passed = true;
      result.code = candidate.code;
      result.source = candidate.source;
      result.verification = verification;
      retainSolution(model, task, candidate.code, candidate.source);
      break;
    }
    result.verification = verification;
  }
  if (!result.passed) {
    recordLearningGoal(model, task, result.verification || { reason: 'all_failed' });
  }
  logPractice(model, task, result);
  return result;
}

/**
 * Run a full self-teaching cycle over seed tasks (and optionally generated
 * variants). Returns a summary.
 */
function runCodingSelfTeachCycle(model, options = {}) {
  const cg = ensureCodeGeneration(model);
  const tasks = options.tasks || CODE_TASK_SEEDS;
  const maxTasks = options.maxTasks || tasks.length;
  const results = [];
  let passed = 0;
  for (const task of tasks.slice(0, maxTasks)) {
    // Skip tasks already mastered (have a retained solution).
    if (!options.retryMastered && cg.solutions.some(s => s.taskId === task.id)) {
      results.push({ taskId: task.id, passed: true, skipped: true });
      passed++;
      continue;
    }
    const r = selfTeachCodingTask(model, task, options);
    results.push({ taskId: task.id, passed: r.passed, source: r.source, reason: r.verification && r.verification.reason });
    if (r.passed) passed++;
  }
  return {
    total: results.length,
    passed,
    failed: results.length - passed,
    solutionsRetained: cg.solutions.length,
    openLearningGoals: cg.learningGoals.filter(g => g.status === 'open').length,
    results
  };
}

/**
 * Answer a user's coding request using the self-teaching machinery.
 * This is the chat bridge: try retained knowledge, then attempt + verify.
 * Returns { answer, code, verified } or null if it cannot do it.
 */
function answerCodingRequest(model, prompt, options = {}) {
  const lower = String(prompt || '').toLowerCase();
  const language = /\bjavascript\b|\bjs\b|\bnode\b/.test(lower) ? 'javascript'
    : /\bpython\b|\bpy\b/.test(lower) ? 'python'
    : 'python'; // default
  // Build an ad-hoc task from the prompt. We can only verify tasks whose
  // expected output we can derive — for now, match against seed tasks.
  // Distinctive keywords (fizzbuzz, fibonacci) count double: they identify
  // the task even when the phrasing differs.
  const taskWords = new Set(lower.split(/\W+/).filter(w => w.length > 3));
  let bestTask = null, bestScore = 0;
  for (const seed of CODE_TASK_SEEDS) {
    if (seed.language !== language) continue;
    const seedWords = new Set(String(seed.description || '').toLowerCase().split(/\W+/).filter(w => w.length > 3));
    let overlap = 0;
    for (const w of taskWords) {
      if (seedWords.has(w)) overlap += w.length >= 7 ? 2 : 1;
    }
    // Tag overlap also counts: it captures the task family.
    const promptTags = [];
    if (/fibonacci/.test(lower)) promptTags.push('sequence');
    if (/fizzbuzz/.test(lower)) promptTags.push('loop');
    if (/factorial/.test(lower)) promptTags.push('math');
    if (/palindrome|reverse/.test(lower)) promptTags.push('string');
    if (/prime/.test(lower)) promptTags.push('math');
    if (/vowel/.test(lower)) promptTags.push('string');
    if (/even|odd/.test(lower)) promptTags.push('condition');
    if (/largest|max|sum/.test(lower)) promptTags.push('math');
    const tagOverlap = (seed.tags || []).filter(t => promptTags.includes(t)).length;
    overlap += tagOverlap;
    if (overlap > bestScore) { bestTask = seed; bestScore = overlap; }
  }
  if (!bestTask || bestScore < 4) return null; // cannot verify: be honest, do not bluff
  const result = selfTeachCodingTask(model, bestTask, { ...options, maxAttempts: 2 });
  if (!result.passed || !result.code) return null;
  const fence = language === 'python' ? 'python' : 'javascript';
  return {
    answer: `Here is working code — I ran it and verified the output:\n\n\`\`\`${fence}\n${result.code}\n\`\`\``,
    code: result.code,
    verified: true,
    taskId: bestTask.id,
    source: result.source
  };
}

module.exports = {
  runCodeSandbox,
  CODE_TASK_SEEDS,
  CODE_PATTERNS,
  generateCandidates,
  verifyAttempt,
  selfTeachCodingTask,
  runCodingSelfTeachCycle,
  answerCodingRequest,
  getRetainedSolutions,
  ensureCodeGeneration,
  getLearnedPatterns,
  addLearnedPattern,
  generalizePattern,
  instantiateLearnedPattern
};
