#!/usr/bin/env node
'use strict';
const crypto = require('crypto'), fs = require('fs'), path = require('path'), { spawnSync } = require('child_process');
const runtime = require('../swarm_model_runtime.js'), neuro = require('../swarm_domain_neurogenesis.js'), mutation = require('../swarm_mutation_repair.js');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'generated-primitive-family-attempt2-20260831');
const BASE_HASH = 'ff0b502c4ce39efea8be53c70eedea9ef47350e884e6400f7adaef14139bf578', ACTIVE_HASH = '91713c42753f32df11df29db70acf78c55c7eb5e9530426913b7fe954eb4e80d';
const BASE = path.join(ROOT, 'consolidation', 'primitive-invention-20260831', 'qualified-candidates', `${BASE_HASH}.json`), PUBLIC = path.join(OUT, 'public-training.json'), SEAL = path.join(OUT, 'sealed-index.json'), MANIFEST = path.join(OUT, 'provisional-candidate-manifest.json'), ACTIVE = path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json'), REGISTRY = path.join(ROOT, 'models', 'lari', 'registry.json');
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex'), shaFile = file => sha(fs.readFileSync(file)), clone = x => JSON.parse(JSON.stringify(x)), rel = file => path.relative(ROOT, file).replace(/\\/g, '/'), assert = (c, m) => { if (!c) throw new Error(m); };
function writeWorkspace(root, files) { for (const [name, content] of Object.entries(files)) { const target = path.join(root, name); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content, { flag: 'wx' }); } }
function run(root, fixture) { const result = spawnSync(fixture.language === 'python' ? 'python' : process.execPath, [fixture.testPath], { cwd: root, encoding: 'utf8', timeout: 10000, windowsHide: true, env: fixture.language === 'python' ? { ...process.env, PYTHONPATH: root } : process.env }); return { passed: result.status === 0, exitCode: result.status, output: `${result.stdout || ''}${result.stderr || ''}`.slice(0, 2000) }; }
function opts(hash, learn, sourcePath) { const shared = { modelHash: hash, sourcePath, benchmarkAssociation: [], allowExpressionOperatorDiscovery: false, allowSemanticOperatorDiscovery: learn, allowPrimitiveDiscovery: false, coordinatedProgramSearch: false, mutationCandidateLimit: 240, mutationProposalLimit: 12, mutationProposalCandidateLimit: 120 }; return { modelHash: hash, autoGrow: false, groundedFactual: false, kernel: { useBenchmarkSystem: false, useCapabilityGraph: true, includeTransientDiagnostics: true, capabilityGraph: { minScore: 0 }, chat: { minMemoryScore: 0, minRouteScore: 0 }, failureLearning: shared, executionContract: { ...shared, workspaceExecution: { maxIterations: 0, ...shared } } } }; }
function request(f, root, id) { return { id, mode: 'code', subintent: 'code.fix', prompt: 'Repair this unfamiliar repository using executable evidence. Exhaust the current mutation vocabulary first. If the vocabulary cannot express the fix, derive a new generic operator family from the failing source, verify the proposed rule against immutable tests, and retain only the rule rather than a file location.', workspaceRoot: root, testPath: f.testPath, testRunner: f.testRunner, expressionTarget: f.expressionTarget, preserveLayout: true }; }
function summary(response) { const failure = response.trace?.find(x => x.phase === 'default_failure_learning'), repair = failure?.frontierFallback?.expressionRepair || response.executionBinding?.workspaceExecution?.expressionRepair || null; return { passed: response.passed === true, modelHash: response.modelHash, repair, hypotheses: response.transientDiagnostics?.hypotheses || [], externalModelCalls: Number(response.external_model_calls || 0) }; }
function main() {
  assert(!fs.existsSync(MANIFEST), 'Generated-family provisional candidate already exists.'); [BASE, PUBLIC, SEAL, ACTIVE, REGISTRY].forEach(f => assert(fs.existsSync(f), `Missing ${rel(f)}`)); assert(shaFile(BASE) === BASE_HASH && shaFile(ACTIVE) === ACTIVE_HASH, 'Protected model hash changed.');
  const seal = JSON.parse(fs.readFileSync(SEAL)), fixture = JSON.parse(fs.readFileSync(PUBLIC)).case, base = JSON.parse(fs.readFileSync(BASE)); assert(shaFile(PUBLIC) === seal.publicTraining.sha256, 'Public seal mismatch.');
  const wanted = JSON.stringify(seal.missingFromBase.rule), baseRules = (base.lariLearnedRecords.records || []).filter(r => r.payload?.operation === 'mutation_vocabulary_rule').map(r => JSON.stringify(r.payload.rule));
  assert(!mutation.DEFAULT_VOCABULARY[seal.missingFromBase.family] && !baseRules.includes(wanted), 'Required family or rule already exists.');
  const protectedBefore = { active: shaFile(ACTIVE), registry: shaFile(REGISTRY), base: shaFile(BASE), public: shaFile(PUBLIC), seal: shaFile(SEAL) };
  const baselineRoot = path.join(OUT, 'baseline-workspace-v5'), learningRoot = path.join(OUT, 'learning-workspace-v5'); writeWorkspace(baselineRoot, fixture.files); writeWorkspace(learningRoot, fixture.files);
  const baselineOracle = shaFile(path.join(baselineRoot, fixture.testPath)), baselineBefore = run(baselineRoot, fixture), baselineResponse = summary(runtime.sendMessageToLari(clone(base), request(fixture, baselineRoot, 'family.baseline'), opts(BASE_HASH, false, 'sealed-family-baseline'))), baselineAfter = run(baselineRoot, fixture);
  const model = clone(base), parentIds = new Set(model.lariLearnedRecords.records.map(r => r.id)); const gap = neuro.createGap(model, { targetType: 'operator', capability: 'derive and retain a generic arithmetic substitution primitive family from executable repository evidence', failureClass: 'mutation_vocabulary_expression_gap', sourceModelHash: BASE_HASH, sourcePath: 'sealed_generated_primitive_family', researchAllowed: true });
  const learningOracle = shaFile(path.join(learningRoot, fixture.testPath)), learningBefore = run(learningRoot, fixture), learningResponse = summary(runtime.sendMessageToLari(model, request(fixture, learningRoot, 'family.learning'), opts(BASE_HASH, true, 'sealed_generated_primitive_family'))), learningAfter = run(learningRoot, fixture);
  const added = model.lariLearnedRecords.records.filter(r => !parentIds.has(r.id) && r.id !== gap.id), vocabulary = added.find(r => r.payload?.operation === 'mutation_vocabulary_rule' && r.payload.family === seal.missingFromBase.family && JSON.stringify(r.payload.rule) === wanted), repair = added.find(r => r.payload?.operation === 'verified_mutation_repair');
  assert(vocabulary, `No generated vocabulary record; added=${added.map(r => `${r.id}:${r.payload?.operation}`).join(',')}; response=${JSON.stringify(learningResponse)}`); assert(repair, 'No verified repair operator retained.');
  model.lineage = { ...(model.lineage || {}), parentHash: BASE_HASH, developmentalEvent: 'sealed_generated_primitive_family_acquisition', createdAt: new Date().toISOString(), sourcePrimitiveId: vocabulary.id, holdoutAccessedBeforeCandidate: false, promoted: false };
  const bytes = Buffer.from(`${JSON.stringify(model, null, 2)}\n`), candidateHash = sha(bytes), candidatePath = path.join(OUT, 'candidates', `${candidateHash}.json`); fs.mkdirSync(path.dirname(candidatePath), { recursive: true }); fs.writeFileSync(candidatePath, bytes, { flag: 'wx' }); const protectedAfter = { active: shaFile(ACTIVE), registry: shaFile(REGISTRY), base: shaFile(BASE), public: shaFile(PUBLIC), seal: shaFile(SEAL) };
  const gates = { absentFromAuthoredVocabulary: !mutation.DEFAULT_VOCABULARY[seal.missingFromBase.family], absentFromBaseModel: !baseRules.includes(wanted), failBeforeAndExistingVocabularyFails: !baselineBefore.passed && !baselineResponse.passed && !baselineAfter.passed, diagnosticBeforeRepair: learningResponse.hypotheses.some(h => h.kind === 'DiagnosticHypothesis'), generatedNewFamily: learningResponse.repair?.grewVocabulary?.family === seal.missingFromBase.family && JSON.stringify(learningResponse.repair.grewVocabulary.rule) === wanted, executableFailToPass: !learningBefore.passed && learningResponse.passed && learningAfter.passed, canonicalTypedPrimitive: vocabulary.type === 'operator' && vocabulary.status === 'active' && vocabulary.payload.operation === 'mutation_vocabulary_rule', ruleNotLocation: !JSON.stringify(vocabulary.payload.rule).includes('capacity') && vocabulary.provenance?.storesSourceCode === false && vocabulary.provenance?.storesTestAnswers === false, oracleImmutable: shaFile(path.join(baselineRoot, fixture.testPath)) === baselineOracle && shaFile(path.join(learningRoot, fixture.testPath)) === learningOracle, gapOpenUntilQualification: gap.status === 'open', hiddenUnread: model.lineage.holdoutAccessedBeforeCandidate === false, candidateHashExact: shaFile(candidatePath) === candidateHash, productionAndBaseReadOnly: JSON.stringify(protectedBefore) === JSON.stringify(protectedAfter), externalModelCallsZero: baselineResponse.externalModelCalls === 0 && learningResponse.externalModelCalls === 0 };
  const manifest = { schemaVersion: 1, kind: 'lari.generated-primitive-family.provisional', createdAt: new Date().toISOString(), parentHash: BASE_HASH, candidate: { path: rel(candidatePath), sha256: candidateHash, promoted: false }, developmental: { gapId: gap.id, primitiveId: vocabulary.id, repairRecordId: repair.id, family: vocabulary.payload.family, rule: vocabulary.payload.rule, baseline: { before: baselineBefore, response: baselineResponse, after: baselineAfter }, learning: { before: learningBefore, response: learningResponse, after: learningAfter } }, seal: { path: rel(SEAL), sha256: shaFile(SEAL), hiddenHash: seal.hiddenHoldouts.sha256 }, gates, passed: Object.values(gates).every(Boolean), protectedBefore, protectedAfter, externalModelCalls: 0, limitations: ['The operator family and rule were proposed from source tokens and verified by executable tests; they were absent from both authored seed vocabulary and the base candidate.', 'The proposal mechanism is still an authored meta-algorithm over source-token substitutions, not unrestricted program induction.', 'Hidden holdouts were not read before candidate creation.'] }; fs.writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`, { flag: 'wx' }); console.log(JSON.stringify({ passed: manifest.passed, candidate: manifest.candidate, primitiveId: vocabulary.id, family: vocabulary.payload.family, rule: vocabulary.payload.rule, gates }, null, 2)); if (!manifest.passed) process.exitCode = 1;
}
main();
