#!/usr/bin/env node
'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path');
const language=require('../swarm_language_understanding.js'),neuro=require('../swarm_domain_neurogenesis.js');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'consolidation','referential-relation-autogenesis-20260901');
const SEAL=path.join(OUT,'sealed-index.json'),TRACES=path.join(OUT,'behavioral-failure-traces.json'),MANIFEST=path.join(OUT,'provisional-candidate-manifest.json');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v)),rel=f=>path.relative(ROOT,f).replace(/\\/g,'/');
function evaluate(model,prompt,expected){const result=language.analyze(prompt,{enableLearningBinding:true,learnedRecords:model.lariLearnedRecords?.records||[]});const relation=(result.semantics.semanticRelations||[]).find(value=>value.type==='ordered_referent');return{passed:relation?.antecedentText===expected,relation:relation||null,operatorIds:result.learnedSemanticOperatorIds||[]};}
function main(){if(fs.existsSync(MANIFEST))throw new Error('Refusing to overwrite provisional referential manifest.');const seal=JSON.parse(fs.readFileSync(SEAL,'utf8'));if(shaFile(TRACES)!==seal.traces.sha256)throw new Error('Behavioral trace seal mismatch.');const basePath=path.join(ROOT,seal.base.path);if(shaFile(basePath)!==seal.base.sha256)throw new Error('Base candidate hash mismatch.');const traces=JSON.parse(fs.readFileSync(TRACES,'utf8')).traces;const model=clone(JSON.parse(fs.readFileSync(basePath,'utf8')));
  const beforeRows=traces.map(item=>({id:item.id,...evaluate(model,item.referentialPrompt,item.expectedEntity)}));if(!beforeRows.every(row=>!row.passed))throw new Error('Gap does not reproduce on every public trace.');
  const gap=neuro.createGap(model,{targetType:'operator',capability:'ordered referential selection',failureClass:'explicit former or latter reference loses its ordered antecedent',sourceModelHash:seal.base.sha256,sourcePath:seal.base.path,occurrences:traces.length});
  const proposal=neuro.proposeCandidate(model,gap,{family:'induced-ordered-reference',referentialFailureTraces:traces},{confidence:0.86,sourceModelHash:seal.base.sha256,sourcePath:seal.base.path,creationSource:'failure_induced_referential_relation_autogenesis'});
  if(!proposal.learned)throw new Error(`Referential synthesis failed: ${proposal.reason}`);model.lariLearnedRecords.records.unshift(proposal.record);model.lineage={...(model.lineage||{}),parentHash:seal.base.sha256,developmentalEvent:'provisional_failure_induced_referential_relation',sourceGapId:gap.id,sourceOperatorId:proposal.record.id,promoted:false};
  const publicRows=traces.map(item=>({id:item.id,...evaluate(model,item.referentialPrompt,item.expectedEntity)}));if(!publicRows.every(row=>row.passed&&row.operatorIds.includes(proposal.record.id)))throw new Error('Synthesized referential operator failed public traces.');
  const bytes=Buffer.from(`${JSON.stringify(model,null,2)}\n`),candidateHash=sha(bytes),candidatePath=path.join(OUT,'provisional-candidates',`${candidateHash}.json`);fs.mkdirSync(path.dirname(candidatePath),{recursive:true});fs.writeFileSync(candidatePath,bytes,{flag:'wx'});fs.chmodSync(candidatePath,0o444);
  const manifest={schemaVersion:1,kind:'lari.referential_relation.provisional_candidate',createdAt:new Date().toISOString(),promoted:false,parentHash:seal.base.sha256,candidate:{path:rel(candidatePath),sha256:candidateHash},gapId:gap.id,operatorId:proposal.record.id,inducedAst:proposal.record.payload.operatorAst,beforeRows,publicRows,gates:{gapReproducedSixOfSix:beforeRows.length===6&&beforeRows.every(row=>!row.passed),noSuppliedOperatorAst:true,markersAndSelectionsInduced:Object.keys(proposal.record.payload.operatorAst.selections||{}).length===2,publicSixOfSix:publicRows.every(row=>row.passed),hiddenNotRead:true,productionUntouched:true,externalModelCallsZero:true}};fs.writeFileSync(MANIFEST,`${JSON.stringify(manifest,null,2)}\n`,{flag:'wx'});fs.chmodSync(MANIFEST,0o444);console.log(JSON.stringify({candidateHash,gapId:gap.id,operatorId:proposal.record.id,inducedAst:manifest.inducedAst,before:'0/6',after:'6/6',hiddenRead:false,promoted:false},null,2));
}
main();
