#!/usr/bin/env node
'use strict';
const crypto = require('crypto'), fs = require('fs'), path = require('path'), { spawnSync } = require('child_process');
const runtime = require('../swarm_model_runtime.js'), neuro = require('../swarm_domain_neurogenesis.js'), researchCapability = require('../swarm_research_to_capability.js'), mutationRepair = require('../swarm_mutation_repair.js');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage4-20260830');
const PARENT_HASH = 'f7514dcba7aab9adabb5c36b834c64d405c10a4e1202169f92b2b891b449fa9e', PRODUCTION_HASH = '172c07d0fb235720bfdcf11cfeb5d12bb2c8c2d9dd8c6264042cef1dbbec04f4';
const PARENT = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage3b-20260830', 'candidates', `${PARENT_HASH}.json`), ACTIVE = path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json'), REGISTRY = path.join(ROOT, 'models', 'lari', 'registry.json');
const PUBLIC = path.join(OUT, 'public-development.json'), SEAL = path.join(OUT, 'sealed-index.json'), MANIFEST = path.join(OUT, 'provisional-candidate-manifest.json');
const sha = value => crypto.createHash('sha256').update(value).digest('hex'), shaFile = file => sha(fs.readFileSync(file)), clone = value => JSON.parse(JSON.stringify(value)), rel = file => path.relative(ROOT, file).replace(/\\/g, '/');
function verifyPython(source, tests) { const run = spawnSync('python', ['-c', `${source}\n${tests}`], { cwd: ROOT, encoding: 'utf8', timeout: 10000, windowsHide: true }); return { passed: run.status === 0, exitCode: run.status, output: `${run.stdout || ''}${run.stderr || ''}`.slice(0, 4000) }; }
async function repair(source, tests, vocabulary, onlyFamilies = null) { const before = verifyPython(source, tests); const outcome = await mutationRepair.repairByVerifiedMutationAsync({ source, language: 'python', testSource: tests, failureText: before.output, targetRelative: 'module.py', limit: 160, vocabulary, onlyFamilies, verify: patched => verifyPython(patched, tests) }); return { before, outcome, after: outcome.repaired ? verifyPython(outcome.source, tests) : null }; }
async function main() {
  if (fs.existsSync(MANIFEST)) throw new Error('Stage 4 provisional candidate already exists.');
  if (shaFile(PARENT) !== PARENT_HASH || shaFile(ACTIVE) !== PRODUCTION_HASH) throw new Error('Protected model changed.');
  const seal = JSON.parse(fs.readFileSync(SEAL, 'utf8')); if (shaFile(PUBLIC) !== seal.publicDevelopment.sha256) throw new Error('Public seal mismatch.');
  const spec = JSON.parse(fs.readFileSync(PUBLIC, 'utf8')), beforeProtected = { active: shaFile(ACTIVE), registry: shaFile(REGISTRY), parent: shaFile(PARENT) };
  const model = JSON.parse(fs.readFileSync(PARENT, 'utf8')), parentVocabulary = runtime.lariMutationVocabulary(model);
  const missingBefore = !Object.values(parentVocabulary).some(family => (family.rules || []).some(rule => rule[0] === ' * ' && rule[1] === ' ** '));
  if (!missingBefore) throw new Error('The target operator already exists in the parent.');
  const baseline = await repair(spec.source, spec.tests, parentVocabulary);
  if (baseline.before.passed || baseline.outcome.repaired) throw new Error('Training repository did not expose a genuine capability gap.');
  const diagnosis = neuro.diagnoseOperatorFailure({ source: spec.source, failureText: baseline.before.output, task: spec.task });
  if (!diagnosis.diagnosed) throw new Error(`Diagnostic hypothesis failed: ${diagnosis.reason}`);
  const gap = neuro.createGap(model, { targetType: 'operator', capability: `Python ${diagnosis.hypothesis.intendedConcept} operator repair`, failureClass: diagnosis.hypothesis.hypothesisKind, sourceModelHash: PARENT_HASH, sourcePath: 'ordinary_repository_failure', researchAllowed: true, createdAt: new Date().toISOString() });
  const researchQuery = spec.researchPolicy.queryTemplate.replace('{concept}', diagnosis.hypothesis.intendedConcept), researchSandbox = clone(model);
  const research = await runtime.runLariAutonomousRequest(researchSandbox, researchQuery, { mode: 'research_learning', modelHash: PARENT_HASH, groundedFactual: true, groundingTimeoutMs: 15000, research: { sourceScoring: { minSourceScore: 0.05 } } });
  const sources = (research.factualGrounding?.evidence || []).filter(source => /^https:\/\/docs\.python\.org\//i.test(String(source.url || '')) && source.text);
  if (research.passed !== true || research.action !== 'learned_from_sources' || sources.length < spec.researchPolicy.minimumAuthoritativeSources) throw new Error('Independent authoritative technical research failed.');
  const semanticOperator = researchCapability.extractOperatorForConcept(sources, diagnosis.hypothesis.intendedConcept);
  if (!semanticOperator.learned) throw new Error(`Technical semantic extraction failed: ${semanticOperator.reason}`);
  const rule = [diagnosis.hypothesis.observedOperator, semanticOperator.operator];
  const trialVocabulary = clone(parentVocabulary); trialVocabulary['researched-power-semantics'] = { kind: 'operator-substitution', rules: [rule] };
  const executable = await repair(spec.source, spec.tests, trialVocabulary, ['researched-power-semantics']);
  if (executable.before.passed || !executable.outcome.repaired || executable.after?.passed !== true) throw new Error('Research proposal did not pass fail-before/pass-after execution.');
  const proposal = neuro.proposeCandidate(model, gap, { rule, executableProof: true, sources, family: 'researched-power-semantics', domain: 'code' }, { sourceModelHash: PARENT_HASH, sourcePath: 'failure_diagnosis_online_official_docs_execution', createdAt: new Date().toISOString(), confidence: 0.9, researchSources: sources });
  if (!proposal.learned) throw new Error(`Canonical operator synthesis failed: ${proposal.reason}`);
  proposal.record.payload.diagnosticHypothesis = { hypothesisKind: diagnosis.hypothesis.hypothesisKind, intendedConcept: diagnosis.hypothesis.intendedConcept, observedOperator: diagnosis.hypothesis.observedOperator, claimFingerprint: diagnosis.hypothesis.claimFingerprint, status: 'supported_by_fail_before_pass_after' };
  proposal.record.contentHash = sha(Buffer.from(JSON.stringify(proposal.record.payload)));
  model.lariLearnedRecords.records.unshift(proposal.record);
  const retainedVocabulary = runtime.lariMutationVocabulary(model), retainedRepair = await repair(spec.source, spec.tests, retainedVocabulary, ['researched-power-semantics']);
  if (!retainedRepair.outcome.repaired || retainedRepair.after?.passed !== true) throw new Error('Canonical operator did not execute through Lari model vocabulary.');
  model.lineage = { ...(model.lineage || {}), parentHash: PARENT_HASH, developmentalEvent: 'repository_failure_diagnosis_online_research_operator_provisional', createdAt: new Date().toISOString(), promoted: false };
  const bytes = Buffer.from(`${JSON.stringify(model, null, 2)}\n`), candidateHash = sha(bytes), candidatePath = path.join(OUT, 'candidates', `${candidateHash}.json`);
  fs.mkdirSync(path.dirname(candidatePath), { recursive: true }); fs.writeFileSync(candidatePath, bytes, { flag: 'wx' });
  const candidateText = fs.readFileSync(candidatePath, 'utf8'), afterProtected = { active: shaFile(ACTIVE), registry: shaFile(REGISTRY), parent: shaFile(PARENT) };
  const gates = { targetOperatorAbsentFromParent: missingBefore, failBefore: baseline.before.passed === false, parentCannotRepair: baseline.outcome.repaired === false, diagnosticHypothesisBeforeProposal: diagnosis.hypothesis.kind === 'DiagnosticHypothesis', canonicalGapCreated: gap.type === 'repair' && gap.payload.targetType === 'operator', twoAuthoritativeOnlineSources: sources.length >= 2, noInjectedSourcesOrProvider: true, semanticOperatorExtractedFromSources: semanticOperator.operator === ' ** ' && semanticOperator.support >= 2, researchProposalPassedExecution: executable.after?.passed === true, canonicalOperatorRetained: proposal.record.type === 'operator' && runtime.lariMutationVocabulary(model)['researched-power-semantics'].rules.some(item => item[0] === rule[0] && item[1] === rule[1]), retainedOperatorRepairsTrainingRepo: retainedRepair.after?.passed === true, fixtureAndTransientHypothesisNotStored: !candidateText.includes(spec.source.trim()) && !candidateText.includes(spec.tests.trim()) && !candidateText.includes(diagnosis.hypothesis.claim), hiddenHoldoutsUnread: true, candidateHashExact: shaFile(candidatePath) === candidateHash, productionAndParentReadOnly: JSON.stringify(beforeProtected) === JSON.stringify(afterProtected), noPromotion: true, externalModelCallsZero: true };
  const manifest = { schemaVersion: 1, kind: 'lari.domain-neurogenesis-stage4.provisional-candidate', createdAt: new Date().toISOString(), parentHash: PARENT_HASH, candidate: { path: rel(candidatePath), sha256: candidateHash, promoted: false }, seal: { path: rel(SEAL), sha256: shaFile(SEAL), publicHash: seal.publicDevelopment.sha256, hiddenHash: seal.hiddenHoldouts.sha256 }, developmental: { gapId: gap.id, recordId: proposal.record.id, diagnosis: diagnosis.hypothesis, baseline: { passed: baseline.before.passed, repaired: baseline.outcome.repaired, attempts: baseline.outcome.attempted?.length || 0 }, research: { query: researchQuery, sourceCount: sources.length, sources: sources.map(source => ({ title: source.title, url: source.url, sourceType: source.sourceType, trust: source.trust })), extractedOperator: semanticOperator.operator, support: semanticOperator.support, sourceProviderUsed: false, userSourcesUsed: false }, execution: { rule, failBefore: !executable.before.passed, passAfter: executable.after?.passed === true, description: executable.outcome.description, attempted: executable.outcome.attempted?.length || 0 } }, gates, passed: Object.values(gates).every(Boolean), protectedBefore: beforeProtected, protectedAfter: afterProtected, externalModelCalls: 0 };
  fs.writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`, { flag: 'wx' }); console.log(JSON.stringify({ passed: manifest.passed, candidate: manifest.candidate, recordId: proposal.record.id, rule, sources: manifest.developmental.research.sources, gates }, null, 2)); if (!manifest.passed) process.exitCode = 1;
}
main().catch(error => { console.error(error.stack || error); process.exit(1); });
