#!/usr/bin/env node
'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const runtime=require('../swarm_model_runtime.js'),registry=require('./lari_model_registry.js');
const root=path.resolve(__dirname,'..'),out=path.join(root,'consolidation','one-hour-apprenticeship-sprint-20260913'),candidateDir=path.join(out,'candidates'),reportPath=path.join(out,'report.json');
const sources=[
 {hash:'ec762123cdb5488604978940ce19a0e63cae03e8af5c3e52cec431110f4a2efb',recordId:'lari.learned.knowledge.dd5dc5557d4a4e7615d12fa1',topic:'Fast Fourier transform'},
 {hash:'eb1472a0000de793fa798e0ca60cc6fd5fac8025142d284be149e31689d79dc1',recordId:'lari.learned.knowledge.e0a3f6aeba76a4e3b38e450a',topic:'Bloom filter'}
];
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v));
const send=(m,p,h)=>runtime.sendMessageToLari(clone(m),p,{modelHash:h,autoGrow:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}});
if(fs.existsSync(reportPath))throw new Error('Refusing to overwrite immutable sprint report.');
const activeBefore=shaFile(registry.currentModelPath),registryBefore=shaFile(registry.registryPath),model=JSON.parse(fs.readFileSync(registry.currentModelPath,'utf8')),imported=[];
for(const source of sources){const sourcePath=path.join(root,'consolidation','learning-candidates',`${source.hash}.json`);assert.strictEqual(shaFile(sourcePath),source.hash);const sourceModel=JSON.parse(fs.readFileSync(sourcePath,'utf8')),record=sourceModel.lariLearnedRecords.records.find(x=>x.id===source.recordId);assert(record);assert(!model.lariLearnedRecords.records.some(x=>x.id===record.id));model.lariLearnedRecords.records.unshift(clone(record));imported.push({...source,sourcePath:path.relative(root,sourcePath).replace(/\\/g,'/')});}
runtime.refreshLariKnowledgeProjections(model,{strict:true});runtime.compileSkills(model,{threshold:.5,limit:420});runtime.refreshLariKnowledgeProjections(model,{strict:true});
model.lineage={...(model.lineage||{}),parentHash:activeBefore,developmentalEvent:'candidate_only_mixed_apprenticeship_sprint',createdAt:new Date().toISOString(),importedRecordIds:imported.map(x=>x.recordId),promoted:false};
const bytes=Buffer.from(`${JSON.stringify(model,null,2)}\n`),candidateHash=sha(bytes);fs.mkdirSync(candidateDir,{recursive:true});const candidatePath=path.join(candidateDir,`${candidateHash}.json`);fs.writeFileSync(candidatePath,bytes,{flag:'wx'});assert.strictEqual(shaFile(candidatePath),candidateHash);const reloaded=JSON.parse(fs.readFileSync(candidatePath,'utf8'));
const prompts=imported.flatMap(x=>[`Explain ${x.topic} in plain language.`,`Why is ${x.topic} useful?`,`State the central idea behind ${x.topic}.`].map(prompt=>({...x,prompt})));
const rows=prompts.map(x=>{const r=send(reloaded,x.prompt,candidateHash);return{topic:x.topic,recordId:x.recordId,prompt:x.prompt,source:r.publicAnswerSource||null,selected:(r.learnedRecordIds||[]).includes(x.recordId),passed:r.publicAnswerSource==='verified_retained_knowledge'&&(r.learnedRecordIds||[]).includes(x.recordId)&&String(r.answer||'').length>=40};});
const ablations=imported.map(x=>{const m=clone(reloaded);m.lariLearnedRecords.records=m.lariLearnedRecords.records.filter(r=>r.id!==x.recordId);runtime.refreshLariKnowledgeProjections(m,{pruneUnboundCompiledSkills:true});const r=send(m,`Explain ${x.topic} in plain language.`,candidateHash);return{recordId:x.recordId,behaviorLost:!(r.learnedRecordIds||[]).includes(x.recordId)};});
const after={active:shaFile(registry.currentModelPath),registry:shaFile(registry.registryPath)},gates={bothRecordsPresent:imported.every(x=>reloaded.lariLearnedRecords.records.some(r=>r.id===x.recordId)),semanticTransfer6of6:rows.length===6&&rows.every(x=>x.passed),reloadRetention:rows.every(x=>x.passed),independentAblation2of2:ablations.every(x=>x.behaviorLost),activeReadOnly:after.active===activeBefore,registryReadOnly:after.registry===registryBefore,noExternalModelCalls:true};
const report={schemaVersion:1,createdAt:new Date().toISOString(),kind:'lari.one-hour-apprenticeship-sprint.cumulative-candidate',parent:{sha256:activeBefore},candidate:{path:path.relative(root,candidatePath).replace(/\\/g,'/'),sha256:candidateHash,promoted:false},imported,rows,ablations,gates,passed:Object.values(gates).every(Boolean),limitations:['This is the first cumulative checkpoint, not an hour-long endurance result.','It proves two factual acquisitions; executable coding acquisition remains separate and bounded.','No production promotion occurred.'],externalModelCalls:0};
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(reportPath,`${JSON.stringify(report,null,2)}\n`,{flag:'wx'});console.log(JSON.stringify({candidateHash,records:imported.map(x=>x.recordId),gates,passed:report.passed},null,2));if(!report.passed)process.exitCode=1;
