#!/usr/bin/env node
'use strict';
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const runtime = require('../swarm_model_runtime.js');
const neuro = require('../swarm_domain_neurogenesis.js');
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage5-20260830');
const PUBLIC = path.join(OUT, 'public-development.json'), SEAL = path.join(OUT, 'sealed-index.json'), MANIFEST = path.join(OUT, 'provisional-candidate-manifest.json');
const PARENT_HASH = '595541d08c308071049ea6bca168260f68c56efdc97a15cb7c96931a8e4b431a', PRODUCTION_HASH = '172c07d0fb235720bfdcf11cfeb5d12bb2c8c2d9dd8c6264042cef1dbbec04f4';
const PARENT = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage4-20260830', 'candidates', `${PARENT_HASH}.json`), ACTIVE = path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json'), REGISTRY = path.join(ROOT, 'models', 'lari', 'registry.json');
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex'), shaFile = file => sha(fs.readFileSync(file)), clone = value => JSON.parse(JSON.stringify(value)), rel = file => path.relative(ROOT, file).replace(/\\/g, '/');
function writeWorkspace(root, files) { for (const [relative, content] of Object.entries(files)) { const target = path.join(root, relative); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content, { flag: 'wx' }); } }
function runFixture(root, fixture) { const executable = fixture.language === 'python' ? 'python' : process.execPath, run = spawnSync(executable, [fixture.testPath], { cwd: root, encoding: 'utf8', timeout: 10000, windowsHide: true, env: fixture.language === 'python' ? { ...process.env, PYTHONPATH: root } : process.env }); return { passed: run.status === 0, exitCode: run.status, output: `${run.stdout || ''}${run.stderr || ''}`.slice(0, 3000) }; }
function options(hash, discovery) { const shared = { modelHash: hash, sourcePath: 'sealed-stage5-public-development', benchmarkAssociation: [], allowExpressionOperatorDiscovery: false, allowSemanticOperatorDiscovery: discovery, coordinatedProgramSearch: true }; return { modelHash: hash, autoGrow: false, groundedFactual: false, kernel: { useBenchmarkSystem: false, useCapabilityGraph: true, includeTransientDiagnostics: true, capabilityGraph: { minScore: 0 }, chat: { minMemoryScore: 0, minRouteScore: 0 }, failureLearning: shared, executionContract: { ...shared, workspaceExecution: { maxIterations: 0, allowExpressionOperatorDiscovery: false, allowSemanticOperatorDiscovery: discovery, coordinatedProgramSearch: true } } } }; }
function summarize(response) { const selected = response.trace?.find(item => item.phase === 'selected_capability_execution') || null, failure = response.trace?.find(item => item.phase === 'default_failure_learning') || null, execution = response.executionBinding?.workspaceExecution || failure?.workspaceExecution || null, repair = selected?.expressionRepair || failure?.frontierFallback?.expressionRepair || execution?.expressionRepair || null, diagnostics = response.transientDiagnostics || execution?.diagnostic || failure?.frontierFallback?.diagnostic || null; return { passed: response.passed === true, action: response.action, modelHash: response.modelHash, repair, recordId: repair?.learnedRecordId || response.executionBinding?.appliedOperatorRecordId || null, diagnosticHypotheses: diagnostics?.hypotheses || [], externalModelCalls: response.external_model_calls || 0 }; }
function main() {
  if (fs.existsSync(MANIFEST)) throw new Error('Stage 5 provisional candidate already exists.');
  if (shaFile(PARENT) !== PARENT_HASH || shaFile(ACTIVE) !== PRODUCTION_HASH) throw new Error('Protected model precondition failed.');
  const seal = JSON.parse(fs.readFileSync(SEAL, 'utf8')); if (shaFile(PUBLIC) !== seal.publicDevelopment.sha256) throw new Error('Public development seal mismatch.');
  const beforeProtected = { parent: shaFile(PARENT), active: shaFile(ACTIVE), registry: shaFile(REGISTRY), public: shaFile(PUBLIC), seal: shaFile(SEAL) };
  const fixture = JSON.parse(fs.readFileSync(PUBLIC, 'utf8')).case, workspace = path.join(OUT, 'training-workspace-attempt-2'); if (fs.existsSync(workspace)) throw new Error('Stage 5 training attempt 2 workspace already exists.');
  writeWorkspace(workspace, fixture.files); const oracle = path.join(workspace, fixture.testPath), oracleHash = shaFile(oracle), before = runFixture(workspace, fixture); if (before.passed) throw new Error('Training fixture must fail before learning.');
  const parent = JSON.parse(fs.readFileSync(PARENT, 'utf8')), model = clone(parent), parentIds = new Set((parent.lariLearnedRecords?.records || []).map(record => record.id));
  const gap = neuro.createGap(model, { targetType: 'procedure', capability: 'coordinated text canonicalization across dependency and consumer', failureClass: 'cross_file_semantic_contract_mismatch', sourceModelHash: PARENT_HASH, sourcePath: 'ordinary_multifile_repository_failure', researchAllowed: true, createdAt: new Date().toISOString() });
  const response = runtime.sendMessageToLari(model, { id: fixture.id, mode: 'code', subintent: 'code.fix', prompt: 'Repair this failing multi-file repository. Form a diagnostic hypothesis, preserve public signatures, coordinate the dependency and consumer, and verify the immutable test.', workspaceRoot: workspace, testPath: fixture.testPath, testRunner: 'javascript.node', expressionTarget: fixture.expressionTarget, preserveLayout: true }, options(PARENT_HASH, true));
  const after = runFixture(workspace, fixture), result = summarize(response); if (!after.passed || !result.passed) throw new Error(`Stage 5 discovery failed: ${JSON.stringify(result)}`);
  const added = model.lariLearnedRecords.records.filter(record => !parentIds.has(record.id) && record.id !== gap.id), record = added[0];
  if (added.length !== 1 || record?.type !== 'procedure' || record?.payload?.operation !== 'coordinated_multi_file_procedure') throw new Error(`Expected one canonical procedure, found ${added.length}.`);
  const serialized = JSON.stringify(record), forbidden = ['canonicalizeLabel', 'uniqueLabels', 'Alpha', 'BETA', 'catalog.test.js', 'DiagnosticHypothesis', 'TransientDiagnosticTrace'];
  model.lineage = { ...(model.lineage || {}), parentHash: PARENT_HASH, developmentalEvent: 'multifile_procedure_neurogenesis_provisional', createdAt: new Date().toISOString(), sourceLearnedRecordId: record.id, holdoutAccessedBeforeCandidate: false, promoted: false };
  const bytes = Buffer.from(`${JSON.stringify(model, null, 2)}\n`), candidateHash = sha(bytes), candidatePath = path.join(OUT, 'candidates', `${candidateHash}.json`); fs.mkdirSync(path.dirname(candidatePath), { recursive: true }); fs.writeFileSync(candidatePath, bytes, { flag: 'wx' });
  const afterProtected = { parent: shaFile(PARENT), active: shaFile(ACTIVE), registry: shaFile(REGISTRY), public: shaFile(PUBLIC), seal: shaFile(SEAL) };
  const gates = { parentGapRecorded: JSON.parse(fs.readFileSync(path.join(OUT, 'parent-gap-probe-v2.json'), 'utf8')).genuineGap === true, trainingFailedBefore: before.passed === false, diagnosticHypothesisBeforeEdit: result.diagnosticHypotheses.some(item => item.kind === 'DiagnosticHypothesis'), searchedSixCompositions: result.repair?.mode === 'searched_coordinated_procedure' && result.repair?.candidateCount === 6, twoFilesChanged: result.repair?.targets?.length === 2, trainingPassedAfter: after.passed === true, immutableOracle: shaFile(oracle) === oracleHash, canonicalProcedureRecord: record.type === 'procedure' && record.payload.procedureAst?.op === 'coordinated_text_canonicalization', composedWinningProcedure: JSON.stringify(record.payload.procedureAst) === JSON.stringify({ op: 'coordinated_text_canonicalization', normalization: ['trim', 'lowercase'], terminal: 'stable_unique' }), noFixtureOrTraceRetention: forbidden.every(term => !serialized.includes(term)), openCanonicalGap: gap.status === 'open' && gap.payload.targetType === 'procedure', candidateHashExact: shaFile(candidatePath) === candidateHash, hiddenHoldoutsUnread: model.lineage.holdoutAccessedBeforeCandidate === false, protectedFilesReadOnly: JSON.stringify(beforeProtected) === JSON.stringify(afterProtected), noPromotion: true, externalModelCallsZero: result.externalModelCalls === 0 };
  const manifest = { schemaVersion: 1, kind: 'lari.domain-neurogenesis-stage5.provisional-candidate', createdAt: new Date().toISOString(), parentHash: PARENT_HASH, candidate: { path: rel(candidatePath), sha256: candidateHash, promoted: false }, seal: { path: rel(SEAL), sha256: shaFile(SEAL), publicHash: seal.publicDevelopment.sha256, hiddenHash: seal.hiddenHoldouts.sha256 }, developmental: { gapId: gap.id, recordId: record.id, training: { before, after, result, oracleSha256: oracleHash }, procedureAst: record.payload.procedureAst }, gates, passed: Object.values(gates).every(Boolean), protectedBefore: beforeProtected, protectedAfter: afterProtected, externalModelCalls: 0, limitations: ['This is one synthesized cross-file text canonicalization procedure family, not arbitrary multi-file coding.', 'The procedure is composed from an authored bounded primitive vocabulary and selected by executable tests.', 'The candidate is not promoted.'] };
  fs.writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`, { flag: 'wx' }); console.log(JSON.stringify({ passed: manifest.passed, candidate: manifest.candidate, gapId: gap.id, recordId: record.id, procedureAst: record.payload.procedureAst, gates }, null, 2)); if (!manifest.passed) process.exitCode = 1;
}
main();
