#!/usr/bin/env node
'use strict';
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage5-promotion-rehearsal-20260830'), SOURCE = path.join(ROOT, 'consolidation', 'domain-neurogenesis-stage5-20260830');
const HASH = '91713c42753f32df11df29db70acf78c55c7eb5e9530426913b7fe954eb4e80d', PRODUCTION_HASH = '172c07d0fb235720bfdcf11cfeb5d12bb2c8c2d9dd8c6264042cef1dbbec04f4';
const files = { candidate: path.join(SOURCE, 'candidates', `${HASH}.json`), qualification: path.join(SOURCE, 'qualification-report.json'), transaction: path.join(OUT, 'promotion-rehearsal-evidence.json'), surfaces: path.join(OUT, 'surface-evidence.json'), active: path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json'), registry: path.join(ROOT, 'models', 'lari', 'registry.json') };
const outputs = { manifest: path.join(OUT, 'rehearsal-manifest.json'), report: path.join(OUT, 'PROMOTION_REHEARSAL_REPORT.md'), rollback: path.join(OUT, 'ROLLBACK_PROCEDURE.md') };
const sha = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'), read = file => JSON.parse(fs.readFileSync(file, 'utf8')), rel = file => path.relative(ROOT, file).replace(/\\/g, '/'), write = (file, value) => fs.writeFileSync(file, typeof value === 'string' ? value : `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx' });
function main() {
  Object.values(outputs).forEach(file => { if (fs.existsSync(file)) throw new Error(`Refusing to overwrite ${rel(file)}`); }); Object.values(files).forEach(file => { if (!fs.existsSync(file)) throw new Error(`Missing ${rel(file)}`); });
  const candidate = read(files.candidate), qualification = read(files.qualification), transaction = read(files.transaction), surfaces = read(files.surfaces), realNow = { active: sha(files.active), registry: sha(files.registry) };
  const gates = { exactCandidateHash: sha(files.candidate) === HASH && qualification.candidate?.sha256 === HASH, qualifiedCandidate: qualification.passed === true && Object.values(qualification.gates || {}).every(Boolean), isolatedPromotion: transaction.gates?.promotionRehearsal === true, exactRollback: transaction.gates?.rollbackRehearsal === true && transaction.rollback?.checks?.restoredPriorHashExactly === true, interruptionSafety: transaction.gates?.interruptedPromotion === true, corruptedCandidateRejected: transaction.gates?.corruptedCandidate === true, noSilentFallback: transaction.gates?.fallbackIsolation === true, coldStartReadOnly: transaction.gates?.coldStart === true, fiveSurfaceParity: surfaces.passed === true && surfaces.gates?.fiveSurfaceAnswerParity === true && surfaces.gates?.fiveSurfaceSelectionParity === true && surfaces.gates?.allSurfacesResolvePromotedHash === true, promotedCloneExecutesProcedure: surfaces.gates?.freshRepositoryPassedAfter === true && surfaces.gates?.promotedProcedureSelected === true && surfaces.gates?.twoFileZeroSearchReuse === true, hiddenTransferReloadAblation: surfaces.gates?.qualificationHiddenTransferFourOfFour === true && surfaces.gates?.qualificationReloadFourOfFour === true && surfaces.gates?.qualificationAblationFourOfFour === true, zeroFamilyRegressions: surfaces.gates?.qualificationNoRegressions === true, realProductionUntouched: realNow.active === PRODUCTION_HASH && JSON.stringify(transaction.realBefore) === JSON.stringify(transaction.realAfter), candidateStillUnpromoted: candidate.lineage?.promoted === false && qualification.candidate?.promoted === false, externalModelCallsZero: qualification.externalModelCalls === 0 && surfaces.externalModelCalls === 0 };
  const passed = Object.values(gates).every(Boolean), verdict = passed ? 'Safe for real promotion' : 'Rehearsal failed';
  const manifest = { schemaVersion: 1, kind: 'lari.domain-neurogenesis-stage5.promotion-rehearsal', createdAt: new Date().toISOString(), rehearsalOnly: true, realPromotionPerformed: false, candidate: { path: rel(files.candidate), sha256: HASH, parentHash: qualification.parentHash }, incumbent: { path: rel(files.active), sha256: PRODUCTION_HASH }, evidence: { qualification: { path: rel(files.qualification), sha256: sha(files.qualification) }, transaction: { path: rel(files.transaction), sha256: sha(files.transaction) }, surfaces: { path: rel(files.surfaces), sha256: sha(files.surfaces) } }, gates, passed, verdict, externalModelCalls: 0, limitations: qualification.limitations };
  write(outputs.manifest, manifest);
  write(outputs.report, `# Lari Stage 5 promotion rehearsal\n\n- Candidate: \`${HASH}\`\n- Production active: \`${PRODUCTION_HASH}\`\n- Real promotion performed: **no**\n- Isolated atomic promotion: **PASS**\n- Exact rollback: **PASS**\n- Interrupted promotion safety: **PASS**\n- Corrupted candidate rejection: **PASS**\n- Silent fallback isolation: **PASS**\n- Cold-start read-only inference: **PASS**\n- Five-surface same-hash answer and selection parity: **4/4 equivalent requests across 5 surfaces**\n- Fresh repository execution through rehearsed active model: **PASS**\n- Hidden transfer / reload / ablation: **4/4 / 4/4 / 4/4**\n- Family regressions: **0**\n- External model calls: **0**\n\nThe rehearsed active model selected \`lari.learned.procedure.coordinated.1f3337c4\` and repaired a fresh two-file Python repository with zero search.\n\n## Honest boundary\n\n- This qualifies promotion mechanics and one bounded learned multi-file procedure.\n- It does not prove arbitrary repository repair or unrestricted procedure invention.\n- The real registry remains unchanged.\n\nVerdict: **${verdict}**\n`);
  write(outputs.rollback, `# Lari Stage 5 rollback procedure\n\nThe isolated rehearsal restored incumbent SHA-256 \`${PRODUCTION_HASH}\` exactly.\n\n1. Verify the active model hash and registry manifest before promotion.\n2. Require the registry backup pointer to hash to \`${PRODUCTION_HASH}\`.\n3. Activate candidate \`${HASH}\` through the existing atomic registry transaction only.\n4. If any gate fails, promote the verified backup with \`rollback: true\`.\n5. Verify the restored active hash equals \`${PRODUCTION_HASH}\`, rollback lineage is recorded, and no temporary activation files remain.\n6. Never use benchmark, root, or candidate paths as silent fallbacks.\n`);
  console.log(JSON.stringify({ passed, verdict, candidate: HASH, incumbent: PRODUCTION_HASH, gates, outputs: Object.fromEntries(Object.entries(outputs).map(([key, file]) => [key, rel(file)])) }, null, 2)); if (!passed) process.exitCode = 1;
}
main();
