#!/usr/bin/env node
'use strict';
const crypto = require('crypto'), fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'generated-primitive-family-promotion-rehearsal-20260831'), HASH = '60d731eb2d04e3411e81c129118b34e372d63311ce39a18c2d47e0e9fd73ac79', INCUMBENT = '91713c42753f32df11df29db70acf78c55c7eb5e9530426913b7fe954eb4e80d';
const files = { candidate: path.join(ROOT, 'consolidation', 'generated-primitive-family-attempt2-20260831', 'qualified-candidates', `${HASH}.json`), qualification: path.join(ROOT, 'consolidation', 'generated-primitive-family-attempt2-20260831', 'qualification-report.json'), transaction: path.join(OUT, 'promotion-rehearsal-evidence.json'), surfaces: path.join(OUT, 'surface-evidence.json'), active: path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json'), registry: path.join(ROOT, 'models', 'lari', 'registry.json') };
const outputs = { manifest: path.join(OUT, 'rehearsal-manifest.json'), report: path.join(OUT, 'PROMOTION_REHEARSAL_REPORT.md'), rollback: path.join(OUT, 'ROLLBACK_PROCEDURE.md') };
const sha = f => crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'), read = f => JSON.parse(fs.readFileSync(f)), rel = f => path.relative(ROOT, f).replace(/\\/g, '/'), write = (f,v) => fs.writeFileSync(f, typeof v === 'string' ? v : `${JSON.stringify(v,null,2)}\n`, { flag:'wx' });
function main() {
  Object.values(outputs).forEach(f => { if(fs.existsSync(f)) throw new Error(`Refusing to overwrite ${rel(f)}`); }); Object.values(files).forEach(f => { if(!fs.existsSync(f)) throw new Error(`Missing ${rel(f)}`); }); const candidate = read(files.candidate), qualification = read(files.qualification), transaction = read(files.transaction), surfaces = read(files.surfaces), realNow = { active: sha(files.active), registry: sha(files.registry) };
  const gates = { exactCandidateHash: sha(files.candidate) === HASH && qualification.qualifiedCandidate?.sha256 === HASH, qualifiedCandidate: qualification.passed === true && Object.values(qualification.gates || {}).every(Boolean), isolatedAtomicPromotion: transaction.gates?.promotionRehearsal === true, exactRollback: transaction.gates?.rollbackRehearsal === true && transaction.rollback?.checks?.restoredPriorHashExactly === true, interruptionSafety: transaction.gates?.interruptedPromotion === true, corruptedCandidateRejected: transaction.gates?.corruptedCandidate === true, noSilentFallback: transaction.gates?.fallbackIsolation === true, coldStartReadOnly: transaction.gates?.coldStart === true, fiveSurfaceSameHashParity: surfaces.passed === true && surfaces.gates?.fiveSurfaceAnswerParity === true && surfaces.gates?.fiveSurfaceSelectionParity === true && surfaces.gates?.allSurfacesResolvePromotedHash === true, freshRepositoryExactPrimitiveExecution: surfaces.gates?.freshRepositoryFailedBefore === true && surfaces.gates?.freshRepositoryPassedAfter === true && surfaces.gates?.promotedProcedureSelected === true && surfaces.executable?.repair?.recordId === 'lari.learned.operator.vocabulary.2dba0034ea8b73f4', hiddenTransferReloadAblation: surfaces.gates?.qualificationHiddenTransferFourOfFour === true && surfaces.gates?.qualificationReloadFourOfFour === true && surfaces.gates?.qualificationAblationFourOfFour === true, zeroFamilyRegressions: surfaces.gates?.qualificationNoRegressions === true, realProductionUntouched: realNow.active === INCUMBENT && transaction.realBefore?.current === transaction.realAfter?.current && transaction.realBefore?.registry === transaction.realAfter?.registry, candidateStillUnpromoted: candidate.lineage?.promoted === false && qualification.qualifiedCandidate?.promoted === false, externalModelCallsZero: qualification.externalModelCalls === 0 && surfaces.externalModelCalls === 0 };
  const passed = Object.values(gates).every(Boolean), verdict = passed ? 'Safe for real promotion' : 'Rehearsal failed'; const manifest = { schemaVersion:1, kind:'lari.generated-primitive-family.promotion-rehearsal', createdAt:new Date().toISOString(), rehearsalOnly:true, realPromotionPerformed:false, candidate:{path:rel(files.candidate),sha256:HASH,parentHash:qualification.parentHash}, incumbent:{path:rel(files.active),sha256:INCUMBENT}, primitive:qualification.primitive, evidence:{qualification:{path:rel(files.qualification),sha256:sha(files.qualification)},transaction:{path:rel(files.transaction),sha256:sha(files.transaction)},surfaces:{path:rel(files.surfaces),sha256:sha(files.surfaces)}}, gates, passed, verdict, externalModelCalls:0, limitations:qualification.limitations }; write(outputs.manifest, manifest);
  write(outputs.report, `# Generated primitive-family promotion rehearsal\n\n- Candidate: \`${HASH}\`\n- Production incumbent: \`${INCUMBENT}\`\n- Real promotion performed: **no**\n- Isolated atomic promotion and exact rollback: **PASS**\n- Interrupted-write safety and corrupted-candidate rejection: **PASS**\n- No silent root, benchmark, or candidate fallback: **PASS**\n- Workbench, CLI, OpenAI-compatible API, autonomous, and canonical parity: **4/4 equivalent prompts**\n- Fresh accumulator repository selected exact primitive \`lari.learned.operator.vocabulary.2dba0034ea8b73f4\`: **PASS**\n- Hidden transfer / cold reload / exact primitive ablation: **4/4 / 4/4 / 4/4**\n- Family regressions: **0**\n- External model calls: **0**\n- Production files changed by rehearsal: **0**\n\n## Honest boundary\n\nThis rehearses the cumulative candidate and its generated arithmetic-substitution primitive. It does not prove unrestricted program induction or arbitrary repository repair.\n\nVerdict: **${verdict}**\n`);
  write(outputs.rollback, `# Generated primitive-family rollback procedure\n\nThe isolated rehearsal restored incumbent SHA-256 \`${INCUMBENT}\` exactly.\n\n1. Verify incumbent active and registry hashes.\n2. Require the backup pointer to resolve to \`${INCUMBENT}\`.\n3. Activate \`${HASH}\` only through the existing atomic registry transaction.\n4. On any failed gate, invoke the same transaction with \`rollback: true\`.\n5. Verify the restored active hash exactly, rollback lineage, and absence of temporary activation files.\n6. Never load root, benchmark, or candidate paths as fallbacks.\n`); console.log(JSON.stringify({passed,verdict,gates,outputs:Object.fromEntries(Object.entries(outputs).map(([k,f])=>[k,rel(f)]))},null,2)); if(!passed) process.exitCode=1;
}
main();
