#!/usr/bin/env node
'use strict';
const crypto = require('crypto'), fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'semantic-ast-promotion-rehearsal-20260831');
const HASH = '9023ab7e28b4ba934ccaa930da146358fe14f4f1ea56a09f857e33f77083efbb', INCUMBENT = 'cab74f590d5ad4533202b1ee2c08b32e28ec47e3c8134ddd24a2bc5bdd7a0fed';
const files = { candidate:path.join(ROOT,'consolidation','semantic-ast-autogenesis-20260831','qualified-candidates',`${HASH}.json`), qualification:path.join(ROOT,'consolidation','semantic-ast-autogenesis-20260831','qualification-report.json'), transaction:path.join(OUT,'promotion-rehearsal-evidence.json'), general:path.join(OUT,'general-surface-evidence.json'), semantic:path.join(OUT,'semantic-surface-evidence.json'), active:path.join(ROOT,'models','lari','current','swarm-model.json'), registry:path.join(ROOT,'models','lari','registry.json') };
const outputs = { manifest:path.join(OUT,'rehearsal-manifest.json'), report:path.join(OUT,'PROMOTION_REHEARSAL_REPORT.md'), rollback:path.join(OUT,'ROLLBACK_PROCEDURE.md') };
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'), read=f=>JSON.parse(fs.readFileSync(f)), rel=f=>path.relative(ROOT,f).replace(/\\/g,'/'), write=(f,v)=>fs.writeFileSync(f,typeof v==='string'?v:`${JSON.stringify(v,null,2)}\n`,{flag:'wx'});
function main(){
  Object.values(outputs).forEach(f=>{if(fs.existsSync(f))throw new Error(`Refusing to overwrite ${rel(f)}`)}); Object.values(files).forEach(f=>{if(!fs.existsSync(f))throw new Error(`Missing ${rel(f)}`)});
  const qualification=read(files.qualification), transaction=read(files.transaction), general=read(files.general), semantic=read(files.semantic), realNow={active:sha(files.active),registry:sha(files.registry)};
  const gates={ exactCandidateHash:sha(files.candidate)===HASH&&qualification.candidateHash===HASH, qualifiedCandidate:qualification.passed===true&&Object.values(qualification.gates||{}).every(Boolean), isolatedAtomicPromotion:transaction.gates?.promotionRehearsal===true, exactRollback:transaction.gates?.rollbackRehearsal===true&&transaction.rollback?.checks?.restoredPriorHashExactly===true, interruptionSafety:transaction.gates?.interruptedPromotion===true, corruptedCandidateRejected:transaction.gates?.corruptedCandidate===true, noSilentFallback:transaction.gates?.fallbackIsolation===true, coldStartReadOnly:transaction.gates?.coldStart===true, generalFiveSurfaceParity:general.nonWorkbenchParityPassed===true&&general.reloadPassed===true&&general.noHiddenWrites===true, semanticFiveSurfaceExactParity:semantic.passed===true&&semantic.gates?.fourPromptsFiveSurfaceExactParity===true, hiddenTransferAndReload:semantic.gates?.hiddenEightOfEight===true&&semantic.gates?.reloadEightOfEight===true&&semantic.gates?.exactAblationEightOfEight===true, zeroFamilyRegressions:general.familyRegression?.passed===true, realProductionUntouched:realNow.active===INCUMBENT&&transaction.realBefore?.current===transaction.realAfter?.current&&transaction.realBefore?.registry===transaction.realAfter?.registry, externalModelCallsZero:semantic.externalModelCalls===0 };
  const passed=Object.values(gates).every(Boolean), verdict=passed?'Safe for real promotion':'Rehearsal failed';
  const manifest={schemaVersion:1,kind:'lari.semantic-ast.promotion-rehearsal',createdAt:new Date().toISOString(),rehearsalOnly:true,realPromotionPerformed:false,candidate:{path:rel(files.candidate),sha256:HASH,parentHash:qualification.parentHash},incumbent:{path:rel(files.active),sha256:INCUMBENT},operator:{id:qualification.operatorId,ast:qualification.inducedAst},evidence:{qualification:{path:rel(files.qualification),sha256:sha(files.qualification)},transaction:{path:rel(files.transaction),sha256:sha(files.transaction)},generalSurfaces:{path:rel(files.general),sha256:sha(files.general)},semanticSurfaces:{path:rel(files.semantic),sha256:sha(files.semantic)}},gates,passed,verdict,externalModelCalls:0,limitations:qualification.limitations}; write(outputs.manifest,manifest);
  write(outputs.report,`# Semantic AST promotion rehearsal\n\n- Candidate: \`${HASH}\`\n- Production incumbent: \`${INCUMBENT}\`\n- Real promotion performed: **no**\n- Isolated atomic promotion and exact rollback: **PASS**\n- Interrupted-write safety and corrupted-candidate rejection: **PASS**\n- No silent root, benchmark, or candidate fallback: **PASS**\n- General five-surface parity: **5/5**\n- Exact semantic-operator parity: **4 prompts across 5/5 surfaces**\n- Semantic hidden transfer / reload / exact ablation: **8/8 / 8/8 / 8/8**\n- Legacy hidden transfer: **17/17**\n- Family regressions: **0**\n- External model calls: **0**\n- Production files changed: **0**\n\n## Honest boundary\n\nThe learned AST covers one postposed conditional-scope family induced from development-authored contrasts. It does not prove unrestricted semantic discovery.\n\nVerdict: **${verdict}**\n`);
  write(outputs.rollback,`# Semantic AST rollback procedure\n\nThe isolated rehearsal restored incumbent SHA-256 \`${INCUMBENT}\` exactly.\n\n1. Verify active and registry hashes.\n2. Require the backup pointer to resolve to \`${INCUMBENT}\`.\n3. Activate \`${HASH}\` only through the existing atomic registry transaction.\n4. On any failed gate, invoke the same transaction with \`rollback: true\`.\n5. Verify exact restored bytes, rollback lineage, and no temporary activation files.\n6. Never use root, benchmark, or candidate paths as fallbacks.\n`);
  Object.values(outputs).forEach(f=>fs.chmodSync(f,0o444)); console.log(JSON.stringify({passed,verdict,gates,outputs:Object.fromEntries(Object.entries(outputs).map(([k,f])=>[k,rel(f)]))},null,2)); if(!passed)process.exitCode=1;
}
main();
