#!/usr/bin/env node
/**
 * Lari fractal composer: the creativity engine core (prototype v1).
 *
 * Pipeline:
 *   1. Pool: grounded seed sentences (authored pool for the demo; phase 2 will
 *      fill this via the research loop's distillSentences). Mirrors the runtime
 *      composer's content-first rule: no sentence may be fabricated from nothing.
 *   2. Grow: seed -> 3 beats (open, turn, land) -> sentences per beat, using
 *      deterministic expansion operators (select, butShift, andWeave). This is
 *      the fractal step: each beat is a smaller copy of the whole arc.
 *   3. Braid: rotate the draft through every giant's lenses in registry order.
 *      Each giant gets one attempt (first passing lens wins); a consistency
 *      gate keeps only transforms that preserve the topic, add no
 *      contradiction, and repeat nothing. Total applications are capped so the
 *      piece stays readable.
 *   4. Verify: every output sentence must carry a derivation chain rooted in
 *      the seed. Anything unverifiable is dropped, never shipped.
 *   5. Label: output is explicitly marked as generated procedural prose.
 *
 * Zero external model calls. No network. Deterministic.
 */
'use strict';

const research = require('./lari_research.js');
const giants = require('./lari_giants.js');
const U = giants.util;

const MAX_BRAID_APPLICATIONS = 10; // backstop only; the per-sentence single-lens
// rule is what preserves readability. Every giant is still attempted.
const CONTRAST_MARKERS = /\b(but|however|yet|still|though|although|despite|while)\b/i;

const LABEL = 'GENERATED BY LARI CREATIVITY ENGINE (prototype v1): ' +
  'procedural recombination of grounded seed sentences through deterministic ' +
  'style lenses. Not human prose.';

function normalize(text) {
  return String(text || '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

// ---------------------------------------------------------------------------
// 1. Pool
// ---------------------------------------------------------------------------

// A seed fragment with no finite verb ("a river cutting through a canyon")
// nominalizes badly under noun-echo lenses ("the cutting gave rise").
// If the polished fragment has no finite verb, convert the first dangling
// -ing participle to a finite present-tense verb. Deterministic and
// conservative: only doubled-consonant stems (cutting -> cut), consonant+y
// stems (flying -> fly), and being -> be are rewritten; everything else is
// left untouched. Third-person -s after "a/an <noun>".
function finiteClause(text) {
  if (U.verbs(text).length > 0) return text;
  const tokens = String(text).match(/[A-Za-z][A-Za-z']*/g) || [];
  for (let i = 0; i < tokens.length; i++) {
    const w = tokens[i].toLowerCase();
    if (w.length <= 4 || !w.endsWith('ing') || U.VERBS.includes(w)) continue;
    let stem = null;
    if (w === 'being') stem = 'be';
    else {
      const doubled = w.match(/^(.+?)([^aeiou])\2ing$/);
      if (doubled) stem = doubled[1] + doubled[2];
      else {
        const ying = w.match(/^(.+[^aeiou])ying$/);
        if (ying) stem = ying[1] + 'y';
      }
    }
    if (!stem) continue;
    const prev = (tokens[i - 1] || '').toLowerCase();
    const prev2 = (tokens[i - 2] || '').toLowerCase();
    let finite = stem;
    if (stem !== 'be' && (prev2 === 'a' || prev2 === 'an') && prev && !prev.endsWith('s')) {
      finite = stem + 's';
    }
    if (/^[A-Z]/.test(tokens[i])) finite = finite.charAt(0).toUpperCase() + finite.slice(1);
    return text.replace(new RegExp('\\b' + tokens[i] + '\\b'), () => finite);
  }
  return text;
}

function buildSeedPool({ topic, seedImage, authoredPool = [] }) {
  const pool = [];
  const seen = new Set();
  const add = (text, ref, polish = false) => {
    let clean = U.sanitize(String(text || '').replace(/\s+/g, ' ').trim());
    if (!clean || clean.length < 12) return;
    // Seed fragments must still read as sentences: finite verb, capitalize, terminate.
    if (polish) clean = finiteClause(clean);
    if (polish && !/[.!?]["']?$/.test(clean)) clean = U.endWith(U.capFirst(clean), '.');
    else if (!/[.!?]["']?$/.test(clean)) clean = U.endWith(clean, '.');
    const key = normalize(clean);
    if (seen.has(key)) return;
    seen.add(key);
    pool.push({ text: clean, derivation: [{ kind: 'seed', ref }] });
  };
  for (const s of U.sentences(seedImage)) add(s, 'seedImage', true);
  for (const s of authoredPool) add(s, 'authored-pool');
  return pool;
}

// ---------------------------------------------------------------------------
// 2. Grow: seed -> beats -> sentences
// ---------------------------------------------------------------------------

function scoreForBeat(item, beat, topicTokens) {
  const text = item.text;
  const words = U.words(text);
  const firstTopicPos = words.findIndex(w => topicTokens.has(w));
  if (beat === 'open') {
    // Establish the topic early.
    return (firstTopicPos >= 0 && firstTopicPos <= 6 ? 10 - firstTopicPos : 0) + (words.length <= 28 ? 2 : 0);
  }
  if (beat === 'turn') {
    // Complicate: contrast markers score highest, then fresh content words.
    return (CONTRAST_MARKERS.test(text) ? 8 : 0) + Math.min(4, U.contentWords(text).length / 3);
  }
  // land: short, declarative, ends with a period.
  return (/[.]$/.test(text) && words.length <= 22 ? 8 : 0) + (U.hasNegation(text) ? -3 : 0);
}

// Deterministic expansion operators. Each returns a new sentence item or null.
function butShift(a, b) {
  const sa = U.stripEnd(a.text);
  const sb = U.lowerFirst(U.stripEnd(b.text));
  if (!sa || !sb || normalize(sa) === normalize(sb)) return null;
  return {
    text: U.sanitize(`${sa}, but ${sb}.`),
    derivation: a.derivation.concat(b.derivation, [{ kind: 'operator', ref: 'butShift' }])
  };
}

function andWeave(a, b) {
  const sa = U.stripEnd(a.text);
  const sb = U.lowerFirst(U.stripEnd(b.text));
  if (!sa || !sb || normalize(sa) === normalize(sb)) return null;
  return {
    text: U.sanitize(`${sa}, and ${sb}.`),
    derivation: a.derivation.concat(b.derivation, [{ kind: 'operator', ref: 'andWeave' }])
  };
}

function growBeats(pool, topic, targetSentences) {
  const topicTokens = new Set(research.topicTokens(`${topic} ${pool.map(p => p.text).join(' ')}`));
  const beats = ['open', 'turn', 'land'];
  const shares = [0.4, 0.35, 0.25];
  const budgets = shares.map(s => Math.max(1, Math.round(targetSentences * s)));
  // Fix rounding so budgets sum exactly to targetSentences.
  let diff = targetSentences - budgets.reduce((a, b) => a + b, 0);
  for (let i = 0; diff !== 0; i = (i + 1) % 3) {
    budgets[i] += Math.sign(diff);
    diff -= Math.sign(diff);
  }

  const used = new Set();
  const result = [];
  beats.forEach((beat, bi) => {
    const ranked = pool
      .map((item, idx) => ({ item, idx, score: scoreForBeat(item, beat, topicTokens) }))
      .filter(c => !used.has(c.idx))
      .sort((a, b) => b.score - a.score || a.idx - b.idx);
    const sentences = [];
    for (const c of ranked) {
      if (sentences.length >= budgets[bi]) break;
      sentences.push({ text: c.item.text, derivation: c.item.derivation.concat([{ kind: 'beat', ref: beat }]) });
      used.add(c.idx);
    }
    // Fractal expansion: recombine pool sentences until the beat budget is met.
    let guard = 0;
    while (sentences.length < budgets[bi] && guard++ < 40) {
      const a = pool[(bi + guard) % pool.length];
      const b = pool[(bi + guard * 2 + 1) % pool.length];
      const made = (beat === 'turn' ? butShift(a, b) : andWeave(a, b));
      if (made && !sentences.some(s => normalize(s.text) === normalize(made.text))) {
        made.derivation = made.derivation.concat([{ kind: 'beat', ref: beat }]);
        sentences.push(made);
      } else break;
    }
    result.push({ name: beat, budget: budgets[bi], sentences });
  });
  return { beats: result, topicTokens };
}

// ---------------------------------------------------------------------------
// 3. Braid: rotate through giant lenses with a consistency gate
// ---------------------------------------------------------------------------

function consistencyGate(candidate, original, draftTexts, topicTokens) {
  if (!candidate || typeof candidate !== 'string') return { pass: false, reason: 'empty' };
  candidate = U.sanitize(candidate.trim());
  if (!candidate) return { pass: false, reason: 'empty' };
  if (normalize(candidate) === normalize(original)) return { pass: false, reason: 'no-op' };
  const wc = U.wordCount(candidate);
  if (wc < 4 || wc > 60) return { pass: false, reason: `word-count=${wc}` };
  const candContent = new Set(U.contentWords(candidate));
  const origContent = U.contentWords(original);
  const shared = origContent.filter(w => candContent.has(w));
  if (!shared.length) return { pass: false, reason: 'topic-drift' };
  const key = normalize(candidate);
  if (draftTexts.some(t => normalize(t) === key)) return { pass: false, reason: 'repeat' };
  // Crude contradiction check: do not negate a content word the original affirmed.
  if (!U.hasNegation(original) && U.hasNegation(candidate)) {
    for (const w of origContent) {
      if (new RegExp(`\\b(not|never|no)\\s+${w}\\b`, 'i').test(candidate)) {
        return { pass: false, reason: 'contradiction' };
      }
    }
  }
  // Topic retention: keep at least one topic token unless the original had none.
  const candTopic = [...candContent].filter(w => topicTokens.has(w));
  const origTopic = origContent.filter(w => topicTokens.has(w));
  if (origTopic.length && !candTopic.length) return { pass: false, reason: 'topic-loss' };
  return { pass: true, candidate };
}

function braid(draft, topicTokens) {
  const texts = draft.map(s => s.text);
  const applied = [];
  const touched = new Set(); // one lens per sentence: stacked lenses read as salad
  for (const giant of giants.listGiants()) {
    let giantApplied = false;
    for (const lens of giant.lenses) {
      if (giantApplied || applied.length >= MAX_BRAID_APPLICATIONS) break;
      const idx = U.hash(`${giant.id}:${lens.id}`) % texts.length;
      if (touched.has(idx)) continue; // this sentence already carries a lens
      const original = texts[idx];
      let candidate;
      try {
        candidate = lens.transform(original, U);
      } catch (_) {
        continue; // a throwing lens is a broken lens; skip it, never crash the braid
      }
      const gate = consistencyGate(candidate, original, texts, topicTokens);
      if (gate.pass) {
        const item = draft[idx];
        item.text = gate.candidate;
        item.derivation = item.derivation.concat([{
          kind: 'lens', ref: `${giant.id}/${lens.id}`, giant: giant.name, lens: lens.name
        }]);
        texts[idx] = gate.candidate;
        touched.add(idx);
        applied.push({
          giantId: giant.id, giantName: giant.name, lensId: lens.id, lensName: lens.name,
          sentenceIndex: idx, before: original, after: gate.candidate
        });
        giantApplied = true;
      }
    }
  }
  return applied;
}

// ---------------------------------------------------------------------------
// 4. Verify traceability
// ---------------------------------------------------------------------------

function verifyTraceability(sentences) {
  const failures = [];
  sentences.forEach((s, i) => {
    if (!Array.isArray(s.derivation) || !s.derivation.length) {
      failures.push({ index: i, reason: 'no-derivation' });
    } else if (s.derivation[0].kind !== 'seed') {
      failures.push({ index: i, reason: 'chain-not-rooted-in-seed' });
    }
  });
  return { ok: failures.length === 0, failures };
}

// ---------------------------------------------------------------------------
// Compose
// ---------------------------------------------------------------------------

function composeCreative({ topic, seedImage, targetSentences = 9, pool: authoredPool = [] }) {
  if (!topic || !seedImage) {
    return { ok: false, honest: 'composeCreative needs a topic and a seedImage; refusing rather than fabricating.' };
  }
  const pool = buildSeedPool({ topic, seedImage, authoredPool });
  if (pool.length < 3) {
    return {
      ok: false,
      honest: `I do not have enough grounded seed content about ${topic} to grow a piece, so I will not pad this with filler.`
    };
  }
  const { beats, topicTokens } = growBeats(pool, topic, targetSentences);
  const draft = [];
  for (const beat of beats) {
    for (const s of beat.sentences) draft.push({ ...s, beat: beat.name });
  }
  const applied = braid(draft, topicTokens);
  const verification = verifyTraceability(draft);
  const piece = draft.map(s => s.text).join(' ');
  const trace = draft.map((s, i) => ({
    index: i,
    beat: s.beat,
    text: s.text,
    chain: s.derivation.map(d => d.kind === 'lens' ? `lens(${d.giant}: ${d.lens})` : `${d.kind}(${d.ref})`).join(' -> ')
  }));
  return {
    ok: true,
    topic, seedImage,
    label: LABEL,
    piece,
    sentences: draft.map(s => s.text),
    trace,
    giantsApplied: applied,
    giantsAttempted: giants.listGiants().length,
    verification,
    external_model_calls: 0
  };
}

module.exports = {
  LABEL,
  buildSeedPool,
  growBeats,
  butShift,
  andWeave,
  braid,
  consistencyGate,
  verifyTraceability,
  composeCreative
};
