#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),runtime=require('../swarm_model_runtime'),registry=require('./lari_model_registry');
const ROOT=path.resolve(__dirname,'..'),EVIDENCE=path.join(ROOT,'benchmarks/latest-lari-public-collection-synthesis-transfer-report.json'),OUT=path.join(ROOT,'benchmarks/latest-lari-collection-synthesis-promotion.json'),DIR=path.join(ROOT,'consolidation/collection-synthesis-promotion-candidates'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),clone=x=>JSON.parse(JSON.stringify(x));
function send(m,p,h){return runtime.sendMessageToLari(clone(m),p,{modelHash:h,autoGrow:false,groundedFactual:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}})}
function main(){
  const evidence=JSON.parse(fs.readFileSync(EVIDENCE)),active=registry.loadLariModel().model,before={active:sha(registry.currentModelPath),registry:sha(registry.registryPath)},record=clone(evidence.record);
  if(!evidence.passed||record.payload?.expressionAst?.op!=='collection_pipeline')throw Error('collection evidence invalid');
  record.payload.languageBindings=['javascript','python'];record.payload.verifiedUses=2;record.provenance={...record.provenance,sourceModelHash:before.active,sourcePath:'models/lari/current/swarm-model.json',classification:'promotion_candidate',promotionEvidence:'benchmarks/latest-lari-public-collection-synthesis-transfer-report.json'};
  const candidate=clone(active);candidate.lariLearnedRecords=candidate.lariLearnedRecords||{schemaVersion:1,records:[]};candidate.lariLearnedRecords.records=[record,...candidate.lariLearnedRecords.records.filter(r=>r.id!==record.id)];candidate.lineage={...(candidate.lineage||{}),parentHash:before.active,developmentalEvent:'collection_synthesis_cross_language_transfer',createdAt:new Date().toISOString()};
  const bytes=Buffer.from(JSON.stringify(candidate,null,2)+'\n'),candidateHash=crypto.createHash('sha256').update(bytes).digest('hex'),candidatePath=path.join(DIR,`${candidateHash}.json`);fs.mkdirSync(DIR,{recursive:true});if(!fs.existsSync(candidatePath))fs.writeFileSync(candidatePath,bytes,{flag:'wx'});
  const reload=JSON.parse(fs.readFileSync(candidatePath)),families=['What are you in plain English?','Give exactly two bullet points about backups.','What is 18 + 27?','Describe safe diagnostics when a test fails.','How should source-grounded learning work?','Why verify destructive changes?'],family=families.map(prompt=>{const a=send(active,prompt,before.active),b=send(reload,prompt,candidateHash);return{promptHash:crypto.createHash('sha256').update(prompt).digest('hex'),regressed:!!a.answer&&!b.answer}}),hidden=(reload.lariLearnedRecords?.records||[]).filter(r=>r.provenance?.imported&&r.type==='knowledge'&&!(r.provenance?.benchmarkAssociation||[]).length&&r.normalizedTriggers?.length>=2).slice(0,17).map(r=>{const q=`What reusable guidance applies when ${r.normalizedTriggers.slice(0,4).join(', ')} matter?`,hits=runtime.searchKnowledge(clone(reload),q,{limit:5,minScore:0})||[];return{id:r.id,passed:hits.some(x=>(x.item?.id||x.id)===r.provenance.originalRecordId)}}),afterValidation={active:sha(registry.currentModelPath),registry:sha(registry.registryPath)},serialized=JSON.stringify(record),ast=record.payload.expressionAst,gates={publicCollectionTransfer:evidence.passed&&evidence.gates.reuseHadZeroSearch,canonicalCollectionAst:record.type==='operator'&&ast.op==='collection_pipeline'&&ast.terminal==='sum'&&ast.filter?.operator==='>',noSourceOrAnswers:/positiveBalance|sum_credits|tmp-lari|workspaceRoot|testPath/.test(serialized)===false,reloadRetention:reload.lariLearnedRecords.records.some(r=>r.id===record.id),crossLanguageBinding:record.payload.languageBindings.length===2&&record.payload.verifiedUses===2,hiddenTransfer17of17:hidden.length===17&&hidden.every(x=>x.passed),zeroFamilyRegressions:family.every(x=>!x.regressed),activeReadOnly:before.active===afterValidation.active,registryReadOnly:before.registry===afterValidation.registry};
  if(!Object.values(gates).every(Boolean))throw Error(`gate failed ${JSON.stringify(gates)}`);
  process.env.LARI_ALLOW_REAL_PROMOTION='1';const promoted=registry.promoteLariModel(candidatePath,{stage:'collection-synthesis-cross-language-transfer',candidateHash,parentHash:before.active,gate:'benchmarks/latest-lari-collection-synthesis-promotion.json',recordId:record.id,externalModelCalls:0});delete process.env.LARI_ALLOW_REAL_PROMOTION;
  const after={active:sha(registry.currentModelPath),registry:sha(registry.registryPath)},report={schemaVersion:1,createdAt:new Date().toISOString(),candidate:{path:path.relative(ROOT,candidatePath).replace(/\\/g,'/'),sha256:candidateHash,parentHash:before.active},record,validation:{gates,family,hiddenTransfer:{passed:hidden.filter(x=>x.passed).length,total:hidden.length}},promotion:{promoted:true,promotedAt:promoted.promotedAt,rollbackPath:promoted.previousModelPath,activeHash:after.active},before,after,passed:after.active===candidateHash};fs.writeFileSync(OUT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,candidate:report.candidate,promotion:report.promotion,gates},null,2));if(!report.passed)process.exitCode=1;
}
main();
