#!/usr/bin/env node
'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path');
const generator=require('../swarm_native_language_generator.js'),language=require('../swarm_language_understanding.js'),runtime=require('../swarm_model_runtime.js');
const ROOT=path.resolve(__dirname,'..'),ACTIVE=path.join(ROOT,'models','lari','current','swarm-model.json'),REGISTRY=path.join(ROOT,'models','lari','registry.json'),OUT=path.join(ROOT,'consolidation','native-language-generator-stage1-20260916');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v)),rel=f=>path.relative(ROOT,f).replace(/\\/g,'/');
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,`${JSON.stringify(v,null,2)}\n`,{flag:'wx'})};
const modelBytes=fs.readFileSync(ACTIVE),registryBytes=fs.readFileSync(REGISTRY),parentHash=sha(modelBytes),registry=JSON.parse(registryBytes);if(registry.activeModelSha256!==parentHash)throw new Error('registry mismatch');
const examples=[['purpose','so that',['action','goal']],['concessive','although',['expectation','assertion']],['temporal_precedence','before',['earlier','later']],['cause','because',['effect','cause']],['contrast','but',['first','second']],['elaboration','and',['first','second']]].map(([relationType,marker,roles])=>({relationType,marker,roles}));
const state=generator.trainState(examples),candidate=JSON.parse(modelBytes);candidate.lariLearnedRecords||={schemaVersion:1,records:[]};
const id='lari.learned.generator.native_language.meaning_to_english.v1';candidate.lariLearnedRecords.records=[{schemaVersion:1,id,type:'generator',status:'active',normalizedTriggers:['meaning graph','language generation','conversation'],procedureIdentity:'native-meaning-to-english-v1',semanticFingerprint:state.contentHash,outputBehavior:'grounded-compositional-english',contentHash:`sha256:${state.contentHash}`,confidence:.9,provenance:{sourceModelHash:parentHash,sourcePath:'computational-english verified production grammar',creationSource:'native_generator_consolidation',benchmarkAssociation:[],storesRawSessionLog:false,storesRawOutputs:false,importTimestamp:new Date().toISOString()},payload:{domain:'general_chat',operation:'native_meaning_to_language',generatorState:state,verification:'claim_trace_grammar_reload_ablation'}},...candidate.lariLearnedRecords.records.filter(r=>r.id!==id)];
candidate.lineage={...(candidate.lineage||{}),type:'native_language_generator_stage1',parentHash,learnedRecordIds:[id],promoted:false,createdAt:new Date().toISOString(),externalModelCalls:0};
const bytes=Buffer.from(`${JSON.stringify(candidate,null,2)}\n`),candidateHash=sha(bytes),candidatePath=path.join(OUT,'candidates',`${candidateHash}.json`);fs.mkdirSync(path.dirname(candidatePath),{recursive:true});fs.writeFileSync(candidatePath,bytes,{flag:'wx'});const reload=JSON.parse(fs.readFileSync(candidatePath));
const subjects=['the team','the gardener','the teacher','the developer','the musician','the neighbor','the researcher','the mechanic','the designer','the student'];
const actions=['checks the evidence','backs up the files','labels the samples','tests the change','writes the plan','reviews the result','records the measurement','asks a question','compares the options','repairs the device'];
const outcomes=['the decision stays reversible','the next person can verify it','the result remains clear','mistakes are caught early','the explanation stays grounded','the work survives a restart','the user can understand it','the claim can be tested','the system keeps its history','the team can learn from failure'];
const types=[['purpose','so that','left_marker_right'],['concessive','although','marker_left_then_right'],['temporal_precedence','before','left_marker_right']];
const cases=[];for(let i=0;i<1000;i++){const [type,marker,surfaceOrder]=types[i%types.length],left=`${subjects[i%subjects.length]} ${actions[(i*3)%actions.length]}`,right=outcomes[(i*7)%outcomes.length];const plan={relations:[{type,marker,surfaceOrder,roles:{left,right}}]};const out=generator.realize(plan,state);cases.push({i,type,passed:out?.verification?.passed===true&&out.answer.toLowerCase().includes(left)&&out.answer.toLowerCase().includes(right),hash:out?.generatorStateHash});}
const clauseCases=[{subject:'I',verb:'help',object:'you'},{subject:'we',verb:'test',object:'changes'},{subject:'users',verb:'understand',object:'results'}].map(roles=>({roles,result:generator.clauseFromRoles(roles)}));
const ablated=clone(reload);ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(r=>r.id!==id);
const ctx={modelHash:candidateHash,autoGrow:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}};const ordinary=runtime.sendMessageToLari(clone(reload),'I had a rough day and feel stuck. Can we talk it through?',ctx);
const after={model:shaFile(ACTIVE),registry:shaFile(REGISTRY)},gates={nativeRecordPresent:reload.lariLearnedRecords.records.some(r=>r.id===id),rawOutputsNotStored:state.training.rawOutputsRetained===false,structuralStress1000Of1000:cases.every(x=>x.passed),verifiedClauseComposition:clauseCases.every(x=>x.result?.text&&x.result.grammarEvidence),reloadRetention:reload.lariLearnedRecords.records.some(r=>r.id===id),exactAblation:!ablated.lariLearnedRecords.records.some(r=>r.id===id),ordinaryChatRegression:ordinary.action==='chat'&&/here with you|talk it through/i.test(ordinary.answer||''),candidateHashExact:shaFile(candidatePath)===candidateHash,activeReadOnly:after.model===parentHash,registryReadOnly:after.registry===sha(registryBytes),externalModelCallsZero:Number(ordinary.external_model_calls||0)===0};
const report={schemaVersion:1,kind:'lari.native-language-generator-stage1.qualification',createdAt:new Date().toISOString(),parentHash,candidate:{path:rel(candidatePath),sha256:candidateHash},recordId:id,stateHash:state.contentHash,clauseCases,structuralStress:{count:cases.length,passed:cases.filter(x=>x.passed).length},gates,passed:Object.values(gates).every(Boolean),promoted:false,limitations:['This is a compositional meaning-to-language generator, not a trained neural decoder.','The 1000-case test is structural stress over generated meaning graphs, not evidence of 1000 conversational abilities.','Open-domain response planning, broad lexical choice, and human-rated conversational quality remain unproven.']};write(path.join(OUT,'qualification.json'),report);console.log(JSON.stringify({candidateHash,gates,passed:report.passed,report:rel(path.join(OUT,'qualification.json'))},null,2));if(!report.passed)process.exitCode=1;
