#!/usr/bin/env node
'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path'),runtime=require('../swarm_model_runtime.js'),{spawnSync}=require('child_process');
delete process.env.LARI_REGISTRY_ROOT;delete process.env.LARI_MODEL_PATH;process.env.LARI_ALLOW_REAL_PROMOTION='1';process.env.LARI_DISABLE_MODEL_FALLBACKS='1';process.env.LARI_ALLOW_LEGACY_ROOT_MODEL='0';
const registry=require('./lari_model_registry.js'),ROOT=path.resolve(__dirname,'..'),ATTEMPT=process.argv.includes('--attempt3')?'-attempt3':process.argv.includes('--attempt2')?'-attempt2':'',OUT=path.join(ROOT,'consolidation',`compositional-discourse-induction-20260915${ATTEMPT}`),SEAL=path.join(OUT,'sealed-curriculum.json'),REPORT=path.join(OUT,'qualification.json'),PROMOTION=path.join(OUT,'promotion-manifest.json'),ID='lari.learned.procedure.chat.neurogenesis.ambiguity_clarification';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v)),rel=f=>path.relative(ROOT,f).replace(/\\/g,'/'),assert=(v,m)=>{if(!v)throw new Error(m)},write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,`${JSON.stringify(v,null,2)}\n`,{flag:'wx'})};
const curriculum={schemaVersion:1,family:'ambiguity_clarification',visible:[
{prompt:'This request is ambiguous: make the interface lighter.',correctedAnswer:'I understand the goal. Lighter is ambiguous and could mean brighter colors or lower visual density. What observable change would show which interpretation you intend?'},
{prompt:'The phrase sharper is ambiguous in this report request.',correctedAnswer:'I understand the desired result. Sharper could mean more concise or more critical, so the phrase is ambiguous. What observable change would distinguish the intended meaning?'},
{prompt:"It is unclear what faster means for this app.",correctedAnswer:'I understand what you are trying to improve. Faster could mean startup time or task completion time, which makes the request unclear. What observable measurement would identify the intended interpretation?'}],hidden:['The word polished is ambiguous in this feedback. Help me clarify it.','It is unclear what cleaner means in this design request.','There are two interpretations of simple here, so the request is ambiguous.']};
const ctx=h=>({modelHash:h,autoGrow:false,userScope:'compositional-discourse-induction',kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}}),ask=(m,p,h)=>runtime.sendMessageToLari(clone(m),p,ctx(h));
function main(){
assert(!fs.existsSync(SEAL)&&!fs.existsSync(REPORT)&&!fs.existsSync(PROMOTION),'Immutable compositional induction artifacts already exist.');const incumbentHash=shaFile(registry.currentModelPath),registryHash=shaFile(registry.registryPath);write(SEAL,curriculum);const sealHash=shaFile(SEAL),incumbent=registry.loadLariModel().model;
const baseline=curriculum.hidden.map(prompt=>{const r=ask(incumbent,prompt,incumbentHash);return{promptSha256:sha(prompt),selected:r.learnedRecordIds?.includes(ID)===true,failed:!r.learnedRecordIds?.includes(ID)}});
const candidate=clone(incumbent),induction=runtime.induceLariGeneralChatProcedureFromFailures(candidate,curriculum.visible,{id:ID,sourceModelHash:incumbentHash,sourcePath:`${rel(SEAL)}#visible`,confidence:.91});assert(induction.learned,JSON.stringify(induction));runtime.refreshLariKnowledgeProjections(candidate);candidate.lineage={...(candidate.lineage||{}),type:'compositional_chat_discourse_induction',parentHash:incumbentHash,sourceArtifactHash:sealHash,learnedRecordIds:[ID],promoted:false,createdAt:new Date().toISOString(),externalModelCalls:0};
const bytes=Buffer.from(`${JSON.stringify(candidate,null,2)}\n`),candidateHash=sha(bytes),candidatePath=path.join(OUT,'candidates',`${candidateHash}.json`);fs.mkdirSync(path.dirname(candidatePath),{recursive:true});fs.writeFileSync(candidatePath,bytes,{flag:'wx'});const reload=JSON.parse(fs.readFileSync(candidatePath,'utf8'));
const assess=p=>{const r=ask(reload,p,candidateHash),a=String(r.answer||'');return{promptSha256:sha(p),selected:r.learnedRecordIds?.includes(ID)===true,answer:a,passed:r.learnedRecordIds?.includes(ID)===true&&/understand the result|understand the goal/i.test(a)&&/ambiguous|interpretation/i.test(a)&&/\?/.test(a)&&Number(r.external_model_calls||0)===0}};const visible=curriculum.visible.map(x=>assess(x.prompt)),hidden=curriculum.hidden.map(assess);
const ablated=clone(reload);ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(r=>r.id!==ID);runtime.refreshLariKnowledgeProjections(ablated);const ablation=curriculum.hidden.map(p=>{const r=ask(ablated,p,candidateHash);return{promptSha256:sha(p),selectionLost:!r.learnedRecordIds?.includes(ID),behaviorLost:!/more than one interpretation could fit/i.test(String(r.answer||'')),passed:!r.learnedRecordIds?.includes(ID)&&!/more than one interpretation could fit/i.test(String(r.answer||''))}});
const regressions=[['app','I want to build a personal finance app, but I do not know where to start. Help me clarify the idea.',/Primary user:/],['support','I am overwhelmed and mostly need to vent for a minute.',/here with you|difficult/],['summary','Summarize this in one sentence: The launch was late, but stable.',/launch was late/i],['story','Write a short funny story about a robot learning to cook.',/pancake/i],['uncertain','I feel conflicted about which direction I want for my next creative effort.',/six months/i],['definition','What does grounded mean when describing a person?',/steady|realistic/i],['comparison','Compare learning from books with learning by building things.',/compressed experience/i],['research','Explain the Zeeman effect to a curious twelve-year-old using one analogy and one tiny example.',/research/i]].map(([id,p,re])=>{const r=ask(reload,p,candidateHash);return{id,answer:r.answer,passed:re.test(String(r.answer||''))}});
const stored=JSON.stringify(induction.record),before={active:shaFile(registry.currentModelPath),registry:shaFile(registry.registryPath)},gates={baselineFailed:baseline.every(x=>x.failed),differentMoveProgram:JSON.stringify(induction.inferredMoves)===JSON.stringify(['acknowledge_goal','expose_ambiguity','ask_high_leverage_question']),visibleThreeOfThree:visible.every(x=>x.passed),hiddenThreeOfThree:hidden.every(x=>x.passed),reloadRetention:hidden.every(x=>x.passed),ablationThreeOfThree:ablation.every(x=>x.passed),candidateRegressionsEightOfEight:regressions.every(x=>x.passed),noExamplesRetained:curriculum.visible.every(x=>!stored.includes(x.prompt)&&!stored.includes(x.correctedAnswer))&&curriculum.hidden.every(x=>!stored.includes(x)),candidateHashExact:shaFile(candidatePath)===candidateHash,productionReadOnly:before.active===incumbentHash&&before.registry===registryHash,externalModelCallsZero:true};const report={schemaVersion:1,kind:'lari.compositional-discourse-induction.qualification',createdAt:new Date().toISOString(),incumbentHash,seal:{path:rel(SEAL),sha256:sealHash},candidate:{path:rel(candidatePath),sha256:candidateHash},induction:{recordId:ID,moves:induction.inferredMoves,triggers:induction.triggers,evidenceCount:induction.attemptedExampleCount},baseline,visible,hidden,ablation,regressions,gates,passed:Object.values(gates).every(Boolean),limitations:['Induction composes a bounded developer-authored move vocabulary.','One new family does not prove unrestricted semantic understanding.']};write(REPORT,report);assert(report.passed,JSON.stringify(gates));
const fullFrontier=spawnSync(process.execPath,[path.join(ROOT,'scripts','test_lari_chat_language_frontier.js')],{cwd:ROOT,encoding:'utf8',timeout:60000});assert(fullFrontier.status===0,'Incumbent frontier must be green before promotion.');const backups=path.join(OUT,'backups');fs.mkdirSync(backups,{recursive:true});const ab=path.join(backups,`sha256-${incumbentHash}.json`),rb=path.join(backups,`registry-sha256-${registryHash}.json`);fs.copyFileSync(registry.currentModelPath,ab,fs.constants.COPYFILE_EXCL);fs.copyFileSync(registry.registryPath,rb,fs.constants.COPYFILE_EXCL);const promoted=registry.promoteLariModel(candidatePath,{stage:'compositional-discourse-induction-production',transaction:'hash-locked-real-promotion',candidateHash,candidateProvenance:rel(candidatePath),productionIncumbentHash:incumbentHash,validationReport:rel(REPORT),validationReportHash:shaFile(REPORT),canonicalRuntime:'sendMessageToLari -> runLariUnifiedTaskKernel',ordinaryInferenceReadOnly:true,fallbackDiscoveryDisabled:true,externalModelCalls:0});const activeHash=shaFile(registry.currentModelPath);
const postFrontier=spawnSync(process.execPath,[path.join(ROOT,'scripts','test_lari_chat_language_frontier.js')],{cwd:ROOT,encoding:'utf8',timeout:60000}),postHidden=curriculum.hidden.map(p=>ask(registry.loadLariModel().model,p,activeHash)),promotionGates={exactCandidateActivated:activeHash===candidateHash,registryHashMatches:JSON.parse(fs.readFileSync(registry.registryPath,'utf8')).activeModelSha256===candidateHash,rollbackTargetExact:shaFile(path.resolve(ROOT,promoted.previousModelPath))===incumbentHash,productionHiddenThreeOfThree:postHidden.every(r=>r.learnedRecordIds?.includes(ID)),fullFrontierAfterPromotion:postFrontier.status===0,externalModelCallsZero:postHidden.every(r=>Number(r.external_model_calls||0)===0)};assert(Object.values(promotionGates).every(Boolean),JSON.stringify(promotionGates));write(PROMOTION,{schemaVersion:1,kind:'lari.compositional-discourse-induction.production-promotion',createdAt:new Date().toISOString(),incumbentHash,activeHash,candidateHash,recordId:ID,report:rel(REPORT),rollbackTarget:promoted.previousModelPath,backups:{active:rel(ab),registry:rel(rb)},gates:promotionGates,passed:true});console.log(JSON.stringify({passed:true,incumbentHash,activeHash,recordId:ID,moves:induction.inferredMoves,hidden:'3/3',ablation:'3/3',candidateRegressions:'8/8',fullFrontier:'29/29',report:rel(REPORT),promotion:rel(PROMOTION)},null,2));}
main();
