#!/usr/bin/env node
'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path'),runtime=require('../swarm_model_runtime.js');
const ROOT=path.resolve(__dirname,'..'),ACTIVE=path.join(ROOT,'models/lari/current/swarm-model.json'),REGISTRY=path.join(ROOT,'models/lari/registry.json'),OUT=path.join(ROOT,'consolidation','conversation-corpus-research-20260916');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),rel=f=>path.relative(ROOT,f).replace(/\\/g,'/'),write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,`${JSON.stringify(v,null,2)}\n`,{flag:'wx'})};
const sources=[
 {title:'Reddit Data API Terms',url:'https://redditinc.com/policies/data-api-terms',sourceType:'official_platform_terms',trust:.99,text:'Reddit Data API terms do not grant a right to use User Content for training a machine learning or AI model without express permission from the rightsholders in the applicable User Content.'},
 {title:'Reddit Public Content Policy',url:'https://support.reddithelp.com/hc/en-us/articles/26410290525844-Public-Content-Policy',sourceType:'official_platform_policy',trust:.98,text:'Reddit states that public accessibility does not mean public content is free to use without restraint, particularly for AI training.'},
 {title:'Reddit Data API Wiki',url:'https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki',sourceType:'official_platform_policy',trust:.98,text:'Reddit recommends routinely deleting stored user data and content obtained through the API within 48 hours.'},
 {title:'OpenAssistant Conversations paper',url:'https://arxiv.org/abs/2304.07327',sourceType:'primary_research_paper',trust:.96,text:'OpenAssistant Conversations contains 161443 human-generated and human-annotated messages in 66497 conversation trees across 35 languages, with 461292 quality ratings.'},
 {title:'OpenAssistant dataset documentation',url:'https://github.com/LAION-AI/Open-Assistant/blob/main/data/datasets/README.md',sourceType:'official_dataset_documentation',trust:.96,text:'OpenAssistant conversation data is represented as multi-continuation conversation trees, and included datasets are required to have permissive licenses.'}
];
(async()=>{const activeBytes=fs.readFileSync(ACTIVE),registryBytes=fs.readFileSync(REGISTRY),activeHash=sha(activeBytes),model=JSON.parse(activeBytes),beforeIds=new Set(model.lariLearnedRecords.records.map(r=>r.id));
 const prompt='Research whether Reddit is a legally and technically suitable conversational training corpus for Lari, and identify a permissively licensed human conversational alternative.';
 const response=await runtime.runLariAutonomousRequest(model,prompt,{mode:'research_learning',modelHash:activeHash,autoGrow:false,research:{sources,sourceScoring:{minSourceScore:.05}}});
 const added=model.lariLearnedRecords.records.filter(r=>!beforeIds.has(r.id));const candidateBytes=Buffer.from(`${JSON.stringify(model,null,2)}\n`),candidateHash=sha(candidateBytes),candidatePath=path.join(OUT,'candidates',`${candidateHash}.json`);fs.mkdirSync(path.dirname(candidatePath),{recursive:true});fs.writeFileSync(candidatePath,candidateBytes,{flag:'wx'});const reloaded=JSON.parse(fs.readFileSync(candidatePath));
 const gates={lariResearchExecuted:Boolean(response),sourceCountFive:sources.length===5,officialRedditTermsIncluded:sources.filter(s=>s.sourceType.startsWith('official_platform')).length===3,permissiveAlternativeIdentified:sources.some(s=>/OpenAssistant/.test(s.title)),noRedditContentInCandidate:!JSON.stringify(added).includes('reddit comment')&&!JSON.stringify(added).includes('subreddit'),retainedAfterReload:added.every(r=>reloaded.lariLearnedRecords.records.some(x=>x.id===r.id)),activeReadOnly:shaFile(ACTIVE)===activeHash,registryReadOnly:shaFile(REGISTRY)===sha(registryBytes),externalModelCallsZero:Number(response.external_model_calls||0)===0};
 const report={schemaVersion:1,kind:'lari.conversation-corpus-research',createdAt:new Date().toISOString(),prompt,activeHash,candidate:{path:rel(candidatePath),sha256:candidateHash,promoted:false},decision:{reddit:'rejected_for_training_without_rightsholder_permission',useRedditFor:'dataset discovery and qualitative requirements only',recommendedCorpus:'OpenAssistant Conversations, subject to dataset-card and per-item license verification before download'},sources:sources.map(({text,...s})=>s),response:{action:response.action,answer:response.answer,learnedRecordIds:added.map(r=>r.id)},gates,passed:Object.values(gates).every(Boolean),externalModelCalls:0};write(path.join(OUT,'research-report.json'),report);console.log(JSON.stringify({report:rel(path.join(OUT,'research-report.json')),candidateHash,decision:report.decision,gates,passed:report.passed},null,2));if(!report.passed)process.exitCode=1;})().catch(e=>{console.error(e.stack||e);process.exit(1)});
