#!/usr/bin/env node
'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process');
const runtime=require('../swarm_model_runtime.js'),neuro=require('../swarm_domain_neurogenesis.js'),registry=require('./lari_model_registry.js');
const ROOT=path.resolve(__dirname,'..'),ACTIVE=registry.currentModelPath,REGISTRY=registry.registryPath,OUT=path.join(ROOT,'consolidation','one-hour-apprenticeship-sprint-20260913'),REPORT=path.join(OUT,'coding-acquisition.json');
const BASE_HASH='d4ee802ce4ff651beda518e04f3480a2f72e19c1ff4a4bda9e7eca662a32d174',BASE=path.join(OUT,'candidates',`${BASE_HASH}.json`),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v));
if(fs.existsSync(REPORT))throw new Error('Refusing to overwrite immutable coding acquisition report.');assert.strictEqual(shaFile(BASE),BASE_HASH);
const protectedBefore={active:shaFile(ACTIVE),registry:shaFile(REGISTRY)};
function write(root,file,text){const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text);}
function fixture(language,name,rows,tag){const root=fs.mkdtempSync(path.join(os.tmpdir(),`lari-sprint-code-${tag}-`));if(language==='javascript'){write(root,'src/value.js',`function ${name}(value) {\n  return value;\n}\nmodule.exports = { ${name} };\n`);write(root,'tests/value.test.js',`const assert=require('assert');const {${name}}=require('../src/value');\n${rows.map(x=>`assert.strictEqual(${name}(${JSON.stringify(x.input)}),${JSON.stringify(x.output)});`).join('\n')}\n`);return{root,language,name,rows,target:'src/value.js',test:'tests/value.test.js',runner:'javascript.node'};}write(root,'src/value.py',`def ${name}(value):\n    return value\n`);write(root,'tests/value_test.py',`import os,sys\nsys.path.insert(0,os.path.dirname(os.path.dirname(__file__)))\nfrom src.value import ${name}\n${rows.map(x=>`assert ${name}(${JSON.stringify(x.input)}) == ${JSON.stringify(x.output)}`).join('\n')}\n`);return{root,language,name,rows,target:'src/value.py',test:'tests/value_test.py',runner:'python.script'};}
function oracle(s){const r=spawnSync(s.language==='python'?'python':process.execPath,[s.test],{cwd:s.root,encoding:'utf8',timeout:15000,windowsHide:true});return r.status===0;}
function run(model,s,discover,hash){const testHash=shaFile(path.join(s.root,s.test)),before=oracle(s),response=runtime.sendMessageToLari(model,{id:`sprint.${s.name}`,mode:'code',subintent:'code.fix',prompt:`Repair ${s.name}: collapse repeated whitespace to one space, reverse the resulting characters, then append the -OK suffix. Preserve the signature and tests.`,workspaceRoot:s.root,testPath:s.test,testRunner:s.runner,expressionTarget:s.target,preserveLayout:true},{modelHash:hash,autoGrow:false,groundedFactual:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,includeTransientDiagnostics:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0},failureLearning:{maxIterations:0,modelHash:hash,sourcePath:'immutable_repository_tests',benchmarkAssociation:[],allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:false,allowPrimitiveDiscovery:discover,coordinatedProgramSearch:false},executionContract:{workspaceExecution:{maxIterations:0,allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:false,allowPrimitiveDiscovery:discover,coordinatedProgramSearch:false}}}});const event=response.trace?.find(x=>x.phase==='default_failure_learning')?.frontierFallback||response.executionBinding?.workspaceExecution||null,repair=event?.expressionRepair||null;return{before,after:oracle(s),oracleImmutable:shaFile(path.join(s.root,s.test))===testHash,response,repair};}
const visible=[{input:'ab  cd',output:'dc ba-OK'},{input:'Moon',output:'nooM-OK'},{input:'x   y z',output:'z y x-OK'}],hidden=[{input:'red   blue',output:'eulb der-OK'},{input:'Orbit',output:'tibrO-OK'},{input:'a  b  c',output:'c b a-OK'}];
const incumbent=JSON.parse(fs.readFileSync(ACTIVE,'utf8')),baseline=run(clone(incumbent),fixture('javascript','encodeTrace',visible,'baseline'),false,protectedBefore.active);assert(!baseline.before&&!baseline.after,'incumbent unexpectedly solved new program');
const candidate=JSON.parse(fs.readFileSync(BASE,'utf8')),idsBefore=new Set(candidate.lariLearnedRecords.records.map(x=>x.id)),learning=run(candidate,fixture('javascript','encodeTrace',visible,'learning'),true,BASE_HASH);assert(!learning.before&&learning.after,JSON.stringify(learning.repair));assert.strictEqual(learning.repair?.mode,'synthesized_declarative_primitive_operator');
const learnedId=learning.repair.learnedRecordId,gapId=learning.repair.capabilityGapId,record=candidate.lariLearnedRecords.records.find(x=>x.id===learnedId),gap=candidate.lariLearnedRecords.records.find(x=>x.id===gapId);assert(record&&gap&&!idsBefore.has(learnedId));assert.deepStrictEqual(record.payload.primitiveAst.steps.map(x=>x.op),['collapse_whitespace','reverse','suffix']);
const hiddenSpec=()=>fixture('python','encode_trace',hidden,`hidden-${Date.now()}-${Math.random()}`),transfer=run(clone(candidate),hiddenSpec(),false,'sprint-provisional'),reload=run(JSON.parse(JSON.stringify(candidate)),hiddenSpec(),false,'sprint-reload');
const ablated=clone(candidate);ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(x=>x.id!==learnedId);const ablation=run(ablated,hiddenSpec(),false,'sprint-ablation');
candidate.lariLearnedRecords.records=candidate.lariLearnedRecords.records.filter(x=>x.id!==learnedId);const retained=neuro.retainVerifiedCandidate(candidate,gap,{learned:true,record},{visible:learning.after&&learning.oracleImmutable,hiddenTransfer:transfer.after,semanticFaithfulness:visible.every(x=>{const e=neuro.executeDeclarativePrimitive(record.payload.primitiveAst,x.input);return e.passed&&e.value===x.output;}),reload:reload.after,ablation:!ablation.after,regressions:0,externalModelCallsZero:true});assert(retained.retained,retained.reason);record.provenance.classification='qualified_candidate';record.provenance.qualificationEvidence='consolidation/one-hour-apprenticeship-sprint-20260913/coding-acquisition.json';
candidate.lineage={...(candidate.lineage||{}),parentHash:protectedBefore.active,developmentalEvent:'candidate_only_mixed_apprenticeship_sprint_with_coding',sourceCandidateHash:BASE_HASH,sourceRecordId:learnedId,promoted:false,createdAt:new Date().toISOString()};const bytes=Buffer.from(`${JSON.stringify(candidate,null,2)}\n`),candidateHash=sha(bytes),candidatePath=path.join(OUT,'candidates',`${candidateHash}.json`);fs.writeFileSync(candidatePath,bytes,{flag:'wx'});const protectedAfter={active:shaFile(ACTIVE),registry:shaFile(REGISTRY)};
const factual=[['Fast Fourier transform','lari.learned.knowledge.dd5dc5557d4a4e7615d12fa1'],['Bloom filter','lari.learned.knowledge.e0a3f6aeba76a4e3b38e450a']].map(([topic,id])=>{const r=runtime.sendMessageToLari(clone(candidate),`Explain ${topic} in plain language.`,{modelHash:candidateHash,autoGrow:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}});return{topic,passed:r.publicAnswerSource==='verified_retained_knowledge'&&(r.learnedRecordIds||[]).includes(id)};});
const gates={incumbentFailed:!baseline.after,visibleFailToPass:!learning.before&&learning.after,learnedNewProgram:!idsBefore.has(learnedId),hiddenPythonTransfer:transfer.after&&transfer.repair?.learnedRecordId===learnedId,coldReload:reload.after&&reload.repair?.learnedRecordId===learnedId,exactAblation:!ablation.after,cumulativeFactsRetained:factual.every(x=>x.passed),immutableCandidate:shaFile(candidatePath)===candidateHash,activeReadOnly:protectedAfter.active===protectedBefore.active,registryReadOnly:protectedAfter.registry===protectedBefore.registry,noExternalModelCalls:true};const report={schemaVersion:1,createdAt:new Date().toISOString(),kind:'lari.one-hour-apprenticeship-sprint.coding-acquisition',parentCandidate:{path:path.relative(ROOT,BASE).replace(/\\/g,'/'),sha256:BASE_HASH},candidate:{path:path.relative(ROOT,candidatePath).replace(/\\/g,'/'),sha256:candidateHash,promoted:false},learnedRecordId:learnedId,gapId,primitiveAst:record.payload.primitiveAst,factual,transfer:{visible:'3/3',hiddenPython:'3/3',reload:'3/3',ablation:'3/3'},gates,passed:Object.values(gates).every(Boolean),limitations:['One unary string transformation family is proven, not arbitrary coding mastery.','The atomic operations already existed; Lari synthesized a new reusable program from them.','Production was not promoted.'],externalModelCalls:0};fs.writeFileSync(REPORT,`${JSON.stringify(report,null,2)}\n`,{flag:'wx'});console.log(JSON.stringify({candidateHash,learnedRecordId:learnedId,program:record.payload.primitiveAst.steps,gates,passed:report.passed},null,2));if(!report.passed)process.exitCode=1;
