'use strict';
// Corrected v2 of the sealed transfer runner. v1 is preserved; this fixes only
// the test-process import path so the oracle exercises Lari's repair.
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const runtime = require('../swarm_model_runtime');
const ROOT = path.resolve(__dirname, '..');
const CANDIDATE = path.join(ROOT, 'consolidation/open-world-apprenticeship-20260901/provisional-candidates/79a80a4ffceb319dce80d63fab35cd11571905b5b31d7f18d2055256cf57461c.json');
const OUT = path.join(ROOT, 'consolidation/provisional-hidden-transfer-20260905-v2.json');
const RECORD = 'lari.learned.operator.semantic_mutation.b1de2702dd1ace54';
const sha = b => crypto.createHash('sha256').update(b).digest('hex'); const fileSha = f => sha(fs.readFileSync(f)); const clone = x => JSON.parse(JSON.stringify(x));
function ws(label) { const r=fs.mkdtempSync(path.join(require('os').tmpdir(),`lari-hidden-v2-${label}-`)); fs.mkdirSync(path.join(r,'src'),{recursive:true}); fs.mkdirSync(path.join(r,'tests'),{recursive:true}); fs.writeFileSync(path.join(r,'src','fields.py'),'def classify(parts):\n    if parts[0] == "widget":\n        return True\n    return False\n'); fs.writeFileSync(path.join(r,'tests','test.py'),'from src.fields import classify\nassert classify(["widget"]) is True\nassert classify(["gadget"]) is True\n'); return r; }
function run(r) { const p=cp.spawnSync('python',['tests/test.py'],{cwd:r,encoding:'utf8',windowsHide:true,env:{...process.env,PYTHONPATH:r}}); return {passed:p.status===0,status:p.status,output:`${p.stdout||''}${p.stderr||''}`.slice(-1500)}; }
function opts(h){const s={modelHash:h,sourcePath:'sealed-hidden-transfer-20260905-v2',benchmarkAssociation:[],allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:false,coordinatedProgramSearch:true};return{modelHash:h,autoGrow:false,groundedFactual:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,includeTransientDiagnostics:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0},failureLearning:s,executionContract:{...s,workspaceExecution:{maxIterations:0,allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:false,coordinatedProgramSearch:true}}}};}
function execute(model,hash,label){const r=ws(label),oracle=fileSha(path.join(r,'tests/test.py')),before=run(r),resp=runtime.sendMessageToLari(model,{id:`hidden.v2.${label}`,mode:'code',subintent:'code.fix',prompt:'Repair this unfamiliar predicate-domain bug. Form a diagnostic hypothesis, preserve the declared test, and verify the fail-to-pass repair.',workspaceRoot:r,testPath:'tests/test.py',testRunner:'python.script',expressionTarget:'src/fields.py',preserveLayout:true},opts(hash)),after=run(r),repair=resp.trace?.find(x=>x.phase==='default_failure_learning')?.frontierFallback?.expressionRepair||null,out={label,before,after,action:resp.action,passed:resp.passed===true,recordId:repair?.learnedRecordId||null,mode:repair?.mode||null,hypotheses:resp.transientDiagnostics?.hypotheses||[],oracleUnchanged:fileSha(path.join(r,'tests/test.py'))===oracle,externalModelCalls:Number(resp.external_model_calls||0)};fs.rmSync(r,{recursive:true,force:true});return out;}
if(fs.existsSync(OUT))throw new Error('immutable output exists'); const bytes=fs.readFileSync(CANDIDATE),hash=sha(bytes),base=JSON.parse(bytes),active=path.join(ROOT,'models/lari/current/swarm-model.json'),registry=path.join(ROOT,'models/lari/registry.json'),before={active:fileSha(active),registry:fileSha(registry),candidate:hash}; const transfer=execute(clone(base),hash,'transfer'),reload=execute(JSON.parse(bytes),hash,'reload'),ablated=clone(base); ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(r=>r.id!==RECORD); const ablation=execute(ablated,hash,'ablation'); const after={active:fileSha(active),registry:fileSha(registry),candidate:fileSha(CANDIDATE)}; const gates={baselineFailed:transfer.before.passed===false,transferPass:transfer.passed&&transfer.after.passed&&transfer.recordId===RECORD,reloadPass:reload.passed&&reload.after.passed&&reload.recordId===RECORD,exactAblationFails:!ablation.passed&&!ablation.after.passed,oracleIntegrity:[transfer,reload,ablation].every(x=>x.oracleUnchanged),noExternalModelCalls:[transfer,reload,ablation].every(x=>x.externalModelCalls===0),productionReadOnly:before.active===after.active&&before.registry===after.registry,candidateUnchanged:before.candidate===after.candidate}; const report={schemaVersion:1,kind:'lari.provisional.hidden-transfer',createdAt:new Date().toISOString(),candidate:{path:path.relative(ROOT,CANDIDATE).replace(/\\/g,'/'),sha256:hash},transfer,reload,ablation,before,after,gates,passed:Object.values(gates).every(Boolean),verdict:Object.values(gates).every(Boolean)?'Hidden transfer qualified; candidate remains unpromoted':'Hidden transfer failed; candidate remains unpromoted'}; fs.writeFileSync(OUT,`${JSON.stringify(report,null,2)}\n`,{flag:'wx'}); console.log(JSON.stringify(report,null,2)); if(!report.passed)process.exitCode=1;
