#!/usr/bin/env node
'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process');
const runtime=require('../swarm_model_runtime.js'),registry=require('./lari_model_registry.js'),{verifySemanticAnswer}=require('./lari_semantic_answer_oracle.js');
const CYCLE=process.argv.includes('--cycle3')?3:process.argv.includes('--cycle2')?2:1;
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'consolidation',CYCLE===3?'sealed-cumulative-apprenticeship-cycle3-20260913':CYCLE===2?'sealed-cumulative-apprenticeship-cycle2-20260913':'sealed-cumulative-apprenticeship-20260913');
const TASKS=path.join(OUT,'tasks.json'),SEAL=path.join(OUT,'seal.json'),REPORT=path.join(OUT,'report.json');
const ACTIVE=registry.currentModelPath,REGISTRY=registry.registryPath,sha=b=>crypto.createHash('sha256').update(b).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),clone=v=>JSON.parse(JSON.stringify(v)),rel=f=>path.relative(ROOT,f).replace(/\\/g,'/');
if(fs.existsSync(REPORT))throw new Error('Refusing to overwrite immutable apprenticeship report.');
const seal=JSON.parse(fs.readFileSync(SEAL)),taskSet=JSON.parse(fs.readFileSync(TASKS));
assert.strictEqual(shaFile(TASKS),seal.tasks.sha256);for(const [file,hash] of Object.entries(seal.runtime))assert.strictEqual(shaFile(path.join(ROOT,file)),hash,`sealed runtime changed: ${file}`);
const basePath=path.join(ROOT,seal.startingCandidate.path);assert.strictEqual(shaFile(basePath),seal.startingCandidate.sha256);
const protectedBefore={active:shaFile(ACTIVE),registry:shaFile(REGISTRY)};
const write=(root,file,text)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text);};
function fixture(task,language,rows,tag){const root=fs.mkdtempSync(path.join(os.tmpdir(),`lari-sealed-${tag}-`));
  if(task.type==='unary_coding'){
    if(language==='javascript'){write(root,'src/value.js','function transformValue(value) {\n  return value;\n}\nmodule.exports={transformValue};\n');write(root,'tests/value.test.js',`const assert=require('assert');const {transformValue}=require('../src/value');\n${rows.map(([i,o])=>`assert.deepStrictEqual(transformValue(${JSON.stringify(i)}),${JSON.stringify(o)});`).join('\n')}\n`);return{root,language,target:'src/value.js',test:'tests/value.test.js',runner:'javascript.node'};}
    write(root,'src/value.py','def transform_value(value):\n    return value\n');write(root,'tests/value_test.py',`import os,sys\nsys.path.insert(0,os.path.dirname(os.path.dirname(__file__)))\nfrom src.value import transform_value\n${rows.map(([i,o])=>`assert transform_value(${JSON.stringify(i)}) == ${JSON.stringify(o)}`).join('\n')}\n`);return{root,language,target:'src/value.py',test:'tests/value_test.py',runner:'python.script'};
  }
  if(language==='javascript'){write(root,'lib/transform.js','function transformEntry(value) {\n  return value;\n}\nmodule.exports={transformEntry};\n');write(root,'src/batch.js',"const {transformEntry}=require('../lib/transform');\nfunction processBatch(values) {\n  return values;\n}\nmodule.exports={processBatch};\n");write(root,'tests/batch.test.js',`const assert=require('assert');const {processBatch}=require('../src/batch');\n${rows.map(([i,o])=>`assert.deepStrictEqual(processBatch(${JSON.stringify(i)}),${JSON.stringify(o)});`).join('\n')}\n`);return{root,language,target:'src/batch.js',test:'tests/batch.test.js',runner:'javascript.node'};}
  write(root,'lib/transform.py','def transform_entry(value):\n    return value\n');write(root,'src/batch.py','from lib.transform import transform_entry\n\ndef process_batch(values):\n    return values\n');write(root,'tests/batch_test.py',`import os,sys\nsys.path.insert(0,os.path.dirname(os.path.dirname(__file__)))\nfrom src.batch import process_batch\n${rows.map(([i,o])=>`assert process_batch(${JSON.stringify(i)}) == ${JSON.stringify(o)}`).join('\n')}\n`);return{root,language,target:'src/batch.py',test:'tests/batch_test.py',runner:'python.script'};
}
function oracle(s){const r=spawnSync(s.language==='python'?'python':process.execPath,[s.test],{cwd:s.root,encoding:'utf8',timeout:20000,windowsHide:true});return{passed:r.status===0,output:`${r.stdout||''}${r.stderr||''}`.slice(-2000)};}
function execute(model,task,language,rows,discover,hash,tag){const spec=fixture(task,language,rows,tag),before=oracle(spec),testHash=shaFile(path.join(spec.root,spec.test));const response=runtime.sendMessageToLari(model,{id:`sealed.${task.id}.${tag}`,mode:'code',subintent:'code.fix',prompt:task.instruction,workspaceRoot:spec.root,testPath:spec.test,testRunner:spec.runner,expressionTarget:spec.target,preserveLayout:true},{modelHash:hash,autoGrow:false,groundedFactual:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,includeTransientDiagnostics:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0},failureLearning:{maxIterations:0,modelHash:hash,sourcePath:`sealed-apprenticeship:${task.id}`,benchmarkAssociation:[],allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:discover,allowPrimitiveDiscovery:discover,coordinatedProgramSearch:task.type==='multifile_coding'},executionContract:{workspaceExecution:{maxIterations:0,allowExpressionOperatorDiscovery:false,allowSemanticOperatorDiscovery:discover,allowPrimitiveDiscovery:discover,coordinatedProgramSearch:task.type==='multifile_coding'}}}});const after=oracle(spec),event=response.executionBinding?.workspaceExecution||response.trace?.find(x=>x.phase==='default_failure_learning')?.frontierFallback||null;return{before:before.passed,after:after.passed,oracleImmutable:shaFile(path.join(spec.root,spec.test))===testHash,repair:event?.expressionRepair||null,learnedRecordIds:response.learnedRecordIds||[],externalModelCalls:Number(response.external_model_calls||0),answer:String(response.answer||'').slice(0,1000)};}
function chat(model,task,hash){const response=runtime.sendMessageToLari(clone(model),task.prompt,{modelHash:hash,autoGrow:false,kernel:{useBenchmarkSystem:false,useCapabilityGraph:true,capabilityGraph:{minScore:0},chat:{minMemoryScore:0,minRouteScore:0}}}),answer=String(response.answer||''),terms=(task.requiredTerms||[]).map(term=>({term,present:answer.toLowerCase().includes(term.toLowerCase())})),semantic=task.semanticContract?verifySemanticAnswer(answer,task.semanticContract):null,requiredRecordSelected=task.requiredRecordId?(response.learnedRecordIds||[]).includes(task.requiredRecordId):null;return{passed:(semantic?semantic.passed:terms.every(x=>x.present))&&(requiredRecordSelected!==false),answer,terms,semantic,requiredRecordSelected,selectedRecordIds:response.learnedRecordIds||[],externalModelCalls:Number(response.external_model_calls||0)};}
let model=JSON.parse(fs.readFileSync(basePath)),currentHash=seal.startingCandidate.sha256;const rows=[],successfulCoding=[];let totalNewRecords=0;
for(const task of taskSet.tasks){
  if(task.type==='chat'){const result=chat(model,task,currentHash);rows.push({id:task.id,type:task.type,result,cumulativeReplay:null});continue;}
  const beforeIds=new Set(model.lariLearnedRecords.records.map(r=>r.id));const acquisition=execute(model,task,'javascript',task.visible,true,currentHash,'learn');const added=model.lariLearnedRecords.records.map(r=>r.id).filter(id=>!beforeIds.has(id));totalNewRecords+=added.length;
  model=JSON.parse(JSON.stringify(model));const transfer=execute(clone(model),task,'python',task.hidden,false,currentHash,'hidden');const primaryId=acquisition.repair?.learnedRecordId||null;let ablation=null;if(primaryId){const ablated=clone(model);ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(r=>r.id!==primaryId);ablation=execute(ablated,task,'javascript',task.hidden,false,currentHash,'ablation');}
  const learned=acquisition.after&&transfer.after&&acquisition.oracleImmutable&&transfer.oracleImmutable&&Boolean(primaryId)&&added.includes(primaryId)&&ablation&&!ablation.after;
  if(learned)successfulCoding.push(task);
  const replay=successfulCoding.map(previous=>{const check=execute(clone(model),previous,'javascript',previous.hidden,false,currentHash,`replay-${task.id}`);return{id:previous.id,passed:check.after,recordId:check.repair?.learnedRecordId||null};});
  rows.push({id:task.id,type:task.type,acquisition,addedRecordIds:added,primaryRecordId:primaryId,transfer,ablation:ablation?{after:ablation.after}:null,learned,cumulativeReplay:replay,reloadPerformed:true});
}
for(const [file,hash] of Object.entries(seal.runtime))assert.strictEqual(shaFile(path.join(ROOT,file)),hash,`runtime changed during sealed run: ${file}`);
model.lineage={...(model.lineage||{}),parentHash:seal.startingCandidate.sha256,developmentalEvent:'sealed_cumulative_apprenticeship',createdAt:new Date().toISOString(),promoted:false};const bytes=Buffer.from(`${JSON.stringify(model,null,2)}\n`),candidateHash=sha(bytes),candidatePath=path.join(OUT,'candidates',`${candidateHash}.json`);fs.mkdirSync(path.dirname(candidatePath),{recursive:true});fs.writeFileSync(candidatePath,bytes,{flag:'wx'});
const protectedAfter={active:shaFile(ACTIVE),registry:shaFile(REGISTRY)},codingRows=rows.filter(r=>r.type!=='chat'),chatRows=rows.filter(r=>r.type==='chat');const gates={sealIntact:shaFile(TASKS)===seal.tasks.sha256,runtimeFrozen:Object.entries(seal.runtime).every(([f,h])=>shaFile(path.join(ROOT,f))===h),allEightAttempted:rows.length===8,codingAcquisitionsAtLeastTwo:codingRows.filter(r=>r.learned).length>=2,hiddenTransferForLearned:codingRows.filter(r=>r.learned).every(r=>r.transfer.after),cumulativeReplay:codingRows.every(r=>(r.cumulativeReplay||[]).every(x=>x.passed)),chatAtLeastThreeOfFour:chatRows.filter(r=>r.result.passed).length>=3,semanticOracleApplied:CYCLE>=2?chatRows.every(r=>Boolean(r.result.semantic)):true,immutableCandidate:shaFile(candidatePath)===candidateHash,activeReadOnly:protectedBefore.active===protectedAfter.active,registryReadOnly:protectedBefore.registry===protectedAfter.registry,noExternalModelCalls:rows.every(r=>r.type==='chat'?r.result.externalModelCalls===0:[r.acquisition,r.transfer].every(x=>x.externalModelCalls===0))};const report={schemaVersion:CYCLE,kind:CYCLE===1?'lari.sealed-cumulative-apprenticeship.result':`lari.sealed-cumulative-apprenticeship-cycle${CYCLE}.result`,createdAt:new Date().toISOString(),seal:{path:rel(SEAL),sha256:shaFile(SEAL)},startingCandidate:seal.startingCandidate,candidate:{path:rel(candidatePath),sha256:candidateHash,promoted:false},summary:{tasksAttempted:rows.length,codingLearned:`${codingRows.filter(r=>r.learned).length}/${codingRows.length}`,chatPassed:`${chatRows.filter(r=>r.result.passed).length}/${chatRows.length}`,newRecordCount:totalNewRecords},rows,gates,passed:Object.values(gates).every(Boolean),verdict:Object.values(gates).every(Boolean)?'Sealed cumulative apprenticeship passed':'Sealed cumulative apprenticeship exposed unresolved capability gaps',protectedBefore,protectedAfter,limitations:['This is an eight-task controlled apprenticeship, not arbitrary open-world mastery.','Task generators and verification harnesses are developer-authored; runtime behavior was frozen before execution.','No candidate was promoted.']};fs.writeFileSync(REPORT,`${JSON.stringify(report,null,2)}\n`,{flag:'wx'});console.log(JSON.stringify({passed:report.passed,verdict:report.verdict,candidateHash,summary:report.summary,gates,taskResults:rows.map(r=>({id:r.id,passed:r.type==='chat'?r.result.passed:r.learned,repair:r.primaryRecordId||null}))},null,2));if(!report.passed)process.exitCode=1;
