#!/usr/bin/env node
'use strict';
const crypto = require('crypto'), fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(ROOT, 'consolidation', 'generated-primitive-family-attempt2-20260831');
const files = { public: path.join(OUT, 'public-training.json'), hidden: path.join(OUT, 'hidden-holdouts.json'), seal: path.join(OUT, 'sealed-index.json') };
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const write = (file, value) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx' }); };
const publicTraining = { schemaVersion: 1, kind: 'lari.generated-primitive-family.public', case: { id: 'public.py.sequence-product', language: 'python', testRunner: 'python.script', testPath: 'tests/check.py', expressionTarget: 'src/product.py', files: { 'src/__init__.py': '', 'src/product.py': 'def sequence_product(values):\n    total = 1\n    for value in values:\n        total = total + value\n    return total\n', 'tests/check.py': "from src.product import sequence_product\nassert sequence_product([3, 4]) == 12\nassert sequence_product([2, 5, 3]) == 30\nassert sequence_product([7, 2]) == 14\nprint('sequence product verified')\n" } } };
const hidden = { schemaVersion: 1, kind: 'lari.generated-primitive-family.hidden', cases: [
  { id: 'hidden.js.factor-product', language: 'javascript', testRunner: 'javascript.node', testPath: 'proof/run.js', expressionTarget: 'lib/factors.js', files: { 'lib/factors.js': 'function factorProduct(values) {\n  let total = 1;\n  for (const value of values) total = total + value;\n  return total;\n}\nmodule.exports = { factorProduct };\n', 'proof/run.js': "const assert = require('assert'); const { factorProduct } = require('../lib/factors'); assert.strictEqual(factorProduct([4, 8]), 32); assert.strictEqual(factorProduct([7, 3]), 21); console.log('factor product verified');\n" } },
  { id: 'hidden.py.score-product', language: 'python', testRunner: 'python.script', testPath: 'proof/check.py', expressionTarget: 'scores/product.py', files: { 'scores/__init__.py': '', 'scores/product.py': 'def score_product(values):\n    result = 1\n    for value in values:\n        result = result + value\n    return result\n', 'proof/check.py': "from scores.product import score_product\nassert score_product([9, 2]) == 18\nassert score_product([5, 5]) == 25\nprint('score product verified')\n" } },
  { id: 'hidden.js.scale-product', language: 'javascript', testRunner: 'javascript.node', testPath: 'checks/check.js', expressionTarget: 'scale/product.js', files: { 'scale/product.js': 'function scaleProduct(parts) {\n  let output = 1;\n  for (const part of parts) output = output + part;\n  return output;\n}\nmodule.exports = { scaleProduct };\n', 'checks/check.js': "const assert = require('assert'); const { scaleProduct } = require('../scale/product'); assert.strictEqual(scaleProduct([6, 9]), 54); assert.strictEqual(scaleProduct([2, 11]), 22); console.log('scale product verified');\n" } },
  { id: 'hidden.py.dimension-product', language: 'python', testRunner: 'python.script', testPath: 'checks/run.py', expressionTarget: 'dimensions/product.py', files: { 'dimensions/__init__.py': '', 'dimensions/product.py': 'def dimension_product(items):\n    aggregate = 1\n    for item in items:\n        aggregate = aggregate + item\n    return aggregate\n', 'checks/run.py': "from dimensions.product import dimension_product\nassert dimension_product([8, 10]) == 80\nassert dimension_product([3, 12]) == 36\nprint('dimension product verified')\n" } }
] };
function main() { if (Object.values(files).some(fs.existsSync)) throw new Error('Generated-primitive-family curriculum already sealed.'); const pb = Buffer.from(`${JSON.stringify(publicTraining, null, 2)}\n`), hb = Buffer.from(`${JSON.stringify(hidden, null, 2)}\n`); write(files.public, publicTraining); write(files.hidden, hidden); write(files.seal, { schemaVersion: 1, kind: 'lari.generated-primitive-family.seal', createdAt: new Date().toISOString(), publicTraining: { path: path.relative(ROOT, files.public).replace(/\\/g, '/'), sha256: sha(pb), cases: 1 }, hiddenHoldouts: { path: path.relative(ROOT, files.hidden).replace(/\\/g, '/'), sha256: sha(hb), cases: 4 }, missingFromBase: { family: 'arithmetic-substitution', rule: [' + ', ' * '] }, learnerMayRead: [path.relative(ROOT, files.public).replace(/\\/g, '/')], learnerMustNotRead: [path.relative(ROOT, files.hidden).replace(/\\/g, '/')] }); console.log(JSON.stringify({ passed: true, publicHash: sha(pb), hiddenHash: sha(hb), hiddenCases: 4 }, null, 2)); }
main();
