#!/usr/bin/env node
'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const recap = require('../swarm_recap_language.js');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'consolidation', 'recap-conversation-expansion-20260830');
const SEAL = path.join(OUT, 'sealed-curriculum.json');
const ACTIVE = path.join(ROOT, 'models', 'lari', 'current', 'swarm-model.json');
const PARENT_HASH = '3b1832fac4a23f4ea616c3e8cca1c59c9fe8d68820775c200bad417b24e81fbb';
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');

const families = [
  {
    id: 'practical_planning',
    train: 'Help me plan how to build a small local note app.',
    hidden: ['Make a plan for learning a new codebase safely.', 'Plan how to prepare a reversible beta release.'],
    markers: ['plan for', 'smallest successful outcome', 'smallest end-to-end version', 'verify']
  },
  {
    id: 'balanced_comparison',
    train: 'Should I rewrite the parser or improve it incrementally?',
    hidden: ['Help me decide between adding features and fixing reliability.', 'Compare local storage versus a small database.'],
    markers: ['versus', 'reversibility', 'tradeoff', 'reversible experiment']
  },
  {
    id: 'requirements_clarification',
    train: 'What do you need to know before you build a personal research assistant?',
    hidden: ['Ask me what you need to know to create a local coding tool.', 'What should you ask me before you make a feedback dashboard?'],
    markers: ['direction', 'primary user', 'success', 'constraints', 'evidence']
  },
  {
    id: 'correction_repair',
    train: 'No, I meant keep the existing API, not replace the whole service.',
    hidden: ['I said archive the candidate, not delete the model.', 'What I mean is test the local runtime, instead of calling an outside model.'],
    markers: ['Understood', 'not', 'correction', 'forward']
  },
  {
    id: 'structured_thinking',
    train: 'Help me think through a beta decision. Context: the model works on bounded tasks. Goal: collect useful feedback. Constraint: do not overstate its abilities.',
    hidden: ['Think through a coding expansion. Context: several repair operators already pass. Goal: handle unfamiliar repositories. Constraint: every retained repair needs causal proof.', 'Help me think through a chat release. Context: procedural answers are reliable. Goal: make conversation feel more natural. Constraint: no outside model calls.'],
    markers: ['relevant context', 'goal', 'constraint', 'reversible step']
  },
  {
    id: 'retained_knowledge_explanation',
    train: 'Tell me about humanize.activate(1000000).',
    hidden: ['What do you know about humanize.activate(1000000)?', 'Explain humanize.activate(1000000).'],
    markers: ['humanize.activate', 'raised', 'Boundary']
  }
];

const payload = {
  schemaVersion: 1,
  kind: 'lari.recap-conversation-expansion.sealed-curriculum',
  sealedAt: new Date().toISOString(),
  parentHash: PARENT_HASH,
  thesis: 'Ordinary conversational moves must be generated by Lari canonical typed records and remain grounded, causally attributable, reloadable, reversible, and local.',
  excludedClaims: ['unrestricted natural-language generation', 'arbitrary factual expertise', 'human-level conversation', 'external model inference'],
  families,
  familyOperations: Object.fromEntries(Object.entries(recap.FAMILIES).filter(([name]) => name !== 'causal_explanation')),
  gates: ['6/6 families train', '12/12 unseen variants', 'every new record causally necessary', 'retained knowledge provenance', 'existing causal RECAP retained', 'five-surface parity', 'hidden transfer 17/17', 'zero family regressions', 'reload', 'rollback', 'read-only inference', 'zero external model calls']
};

if (fs.existsSync(SEAL)) throw new Error('Conversation curriculum is already sealed.');
if (sha(fs.readFileSync(ACTIVE)) !== PARENT_HASH) throw new Error('Active parent hash changed.');
fs.mkdirSync(OUT, { recursive: true });
const bytes = Buffer.from(`${JSON.stringify(payload, null, 2)}\n`);
fs.writeFileSync(SEAL, bytes, { flag: 'wx' });
console.log(JSON.stringify({ path: path.relative(ROOT, SEAL).replace(/\\/g, '/'), sha256: sha(bytes), families: families.length, hidden: families.reduce((sum, family) => sum + family.hidden.length, 0), parentHash: PARENT_HASH }, null, 2));

