#!/usr/bin/env node
'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path');
const language=require('../swarm_language_understanding.js');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'consolidation','referential-relation-autogenesis-20260901');
const MANIFEST=path.join(OUT,'qualified-candidate-manifest.json'),REPORT=path.join(OUT,'qualification-report.json'),HIDDEN=path.join(OUT,'hidden-holdouts.json'),BASELINE=path.join(OUT,'baseline-evidence.json');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),assert=(v,m)=>{if(!v)throw new Error(m)},evaluate=(model,item)=>{const result=language.analyze(item.prompt,{enableLearningBinding:true,learnedRecords:model.lariLearnedRecords?.records||[]});const relation=(result.semantics.semanticRelations||[]).find(value=>value.type==='ordered_referent');return relation?.antecedentText===item.expectedEntity};
function main(){const manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),report=JSON.parse(fs.readFileSync(REPORT,'utf8')),baseline=JSON.parse(fs.readFileSync(BASELINE,'utf8')),hidden=JSON.parse(fs.readFileSync(HIDDEN,'utf8')).cases,candidatePath=path.join(ROOT,manifest.candidate.path);assert(sha(candidatePath)===manifest.candidate.sha256,'Qualified candidate hash mismatch.');assert(report.passed&&Object.values(report.gates||{}).every(Boolean),'Qualification gates are not all green.');assert(baseline.gates?.currentPrimitiveLanguageCannotExpress&&baseline.rows.every(row=>!row.passed),'Baseline gap was not preserved.');const candidate=JSON.parse(fs.readFileSync(candidatePath,'utf8')),rows=hidden.map(item=>evaluate(candidate,item));assert(rows.every(Boolean),'Hidden transfer no longer passes.');const ablated=JSON.parse(JSON.stringify(candidate));ablated.lariLearnedRecords.records=ablated.lariLearnedRecords.records.filter(record=>record.id!==manifest.operatorId);assert(hidden.every(item=>!evaluate(ablated,item)),'Exact operator ablation no longer fails.');const executor=fs.readFileSync(path.join(ROOT,'swarm_language_understanding.js'),'utf8').toLowerCase();assert(!executor.includes("'former'")&&!executor.includes("'latter'"),'Executor hardcodes learned referential markers.');console.log(JSON.stringify({passed:true,candidateHash:manifest.candidate.sha256,operatorId:manifest.operatorId,hidden:'8/8',ablation:'8/8',executorMarkerAgnostic:true,externalModelCalls:0},null,2));}
main();
